package us.eunoians.mcrpg.statistic;

import com.diamonddagger590.mccore.statistic.SimpleStatistic;
import com.diamonddagger590.mccore.statistic.Statistic;
import com.diamonddagger590.mccore.statistic.StatisticType;
import org.bukkit.NamespacedKey;
import org.jetbrains.annotations.NotNull;
import us.eunoians.mcrpg.util.McRPGMethods;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * All McRPG-tracked statistics, defined as constants. Follows the same pattern
 * as {@link us.eunoians.mcrpg.entity.player.McRPGSetting} for player settings.
 * <p>
 * Statistics are registered during bootstrap via
 * {@link us.eunoians.mcrpg.expansion.content.StatisticContentPack} in the
 * {@link us.eunoians.mcrpg.expansion.ContentExpansion} system.
 * <p>
 * <b>Note on display names and descriptions:</b> The {@code displayName} and
 * {@code description} fields on each statistic are plain-English metadata used for
 * internal/admin-facing purposes (e.g., debug commands, database inspection, admin UIs).
 * They are <b>not</b> player-facing chat text and therefore do not need to go through the
 * localization system. If statistics are ever surfaced in player-visible messages or GUIs,
 * those messages should use
 * {@link us.eunoians.mcrpg.configuration.file.localization.LocalizationKey} entries that
 * reference the statistic by its {@link org.bukkit.NamespacedKey} rather than displaying
 * these fields directly.
 */
public final class McRPGStatistic {

    private McRPGStatistic() {
        // Utility class — no instantiation
    }

    private static final String NAMESPACE = McRPGMethods.getMcRPGNamespace();

    /** Total blocks mined that grant skill XP (any skill). */
    public static final Statistic BLOCKS_MINED = longStat("blocks_mined",
            "Blocks Mined", "Total blocks mined that grant skill XP");

    /** Ore blocks specifically. */
    public static final Statistic ORES_MINED = longStat("ores_mined",
            "Ores Mined", "Ore blocks mined");

    /** Logs broken that grant skill XP. */
    public static final Statistic TREES_CHOPPED = longStat("trees_chopped",
            "Trees Chopped", "Logs broken that grant skill XP");

    /** Crops harvested that grant skill XP. */
    public static final Statistic CROPS_HARVESTED = longStat("crops_harvested",
            "Crops Harvested", "Crops harvested that grant skill XP");

    /** Total mobs killed (any combat). */
    public static final Statistic MOBS_KILLED = longStat("mobs_killed",
            "Mobs Killed", "Total mobs killed");

    /** Total damage dealt (all sources). */
    public static final Statistic DAMAGE_DEALT = new SimpleStatistic(
            key("damage_dealt"), StatisticType.DOUBLE, 0.0,
            "Damage Dealt", "Total damage dealt");

    /** Total damage taken (all sources). */
    public static final Statistic DAMAGE_TAKEN = new SimpleStatistic(
            key("damage_taken"), StatisticType.DOUBLE, 0.0,
            "Damage Taken", "Total damage taken");

    /** Sum of all levels gained across all skills. */
    public static final Statistic TOTAL_SKILL_LEVELS_GAINED = longStat("total_skill_levels_gained",
            "Total Skill Levels Gained", "Sum of all levels gained across all skills");

    /** Sum of all XP earned across all skills (including overflow). */
    public static final Statistic TOTAL_SKILL_EXPERIENCE = longStat("total_skill_experience",
            "Total Skill Experience", "Sum of all XP earned across all skills");

    /** Total ability activations across all abilities. */
    public static final Statistic ABILITIES_ACTIVATED = longStat("abilities_activated",
            "Abilities Activated", "Total ability activations across all abilities");

    /**
     * All statically-defined global statistics. Does not include per-skill statistics
     * (which are generated by each skill's {@link us.eunoians.mcrpg.skill.Skill#getDefaultStatistics()})
     * or per-ability activation statistics (generated by
     * {@link us.eunoians.mcrpg.ability.impl.type.ActiveAbility#getDefaultStatistics()}).
     */
    public static final Set<Statistic> ALL_STATIC_STATISTICS;

    static {
        Set<Statistic> stats = new LinkedHashSet<>();
        // Global gameplay
        stats.add(BLOCKS_MINED);
        stats.add(ORES_MINED);
        stats.add(TREES_CHOPPED);
        stats.add(CROPS_HARVESTED);
        stats.add(MOBS_KILLED);
        stats.add(DAMAGE_DEALT);
        stats.add(DAMAGE_TAKEN);
        // Skill progression (global totals only — per-skill stats come from Skill.getDefaultStatistics())
        stats.add(TOTAL_SKILL_LEVELS_GAINED);
        stats.add(TOTAL_SKILL_EXPERIENCE);
        // Ability (global total — per-ability stats come from ActiveAbility.getDefaultStatistics())
        stats.add(ABILITIES_ACTIVATED);
        ALL_STATIC_STATISTICS = Collections.unmodifiableSet(stats);
    }

    /**
     * Gets the per-skill experience statistic key for a given skill key.
     * <p>
     * Example: {@code getSkillExperienceKey(Mining.MINING_KEY)} returns
     * the key {@code mcrpg:mining_experience}.
     *
     * @param skillKey The skill's {@link NamespacedKey}.
     * @return The experience statistic key for the given skill.
     */
    @NotNull
    public static NamespacedKey getSkillExperienceKey(@NotNull NamespacedKey skillKey) {
        return key(skillKey.getKey() + "_experience");
    }

    /**
     * Gets the per-skill max level statistic key for a given skill key.
     * <p>
     * Example: {@code getSkillMaxLevelKey(Mining.MINING_KEY)} returns
     * the key {@code mcrpg:mining_max_level}.
     *
     * @param skillKey The skill's {@link NamespacedKey}.
     * @return The max level statistic key for the given skill.
     */
    @NotNull
    public static NamespacedKey getSkillMaxLevelKey(@NotNull NamespacedKey skillKey) {
        return key(skillKey.getKey() + "_max_level");
    }

    /**
     * Gets the per-ability activation count statistic key for a given ability key.
     * <p>
     * Example: {@code getAbilityActivationKey(Bleed.BLEED_KEY)} returns
     * the key {@code mcrpg:bleed_activations}.
     *
     * @param abilityKey The ability's {@link NamespacedKey}.
     * @return The activation count statistic key for the given ability.
     */
    @NotNull
    public static NamespacedKey getAbilityActivationKey(@NotNull NamespacedKey abilityKey) {
        return key(abilityKey.getKey() + "_activations");
    }

    /**
     * Creates a per-ability activation {@link Statistic} definition for dynamic registration.
     * <p>
     * The generated display name and description are admin-facing metadata — see the class-level
     * javadoc for why they are not localized.
     *
     * @param abilityKey   The ability's {@link NamespacedKey}.
     * @param displayName  The human-readable ability name (used for the statistic display name).
     * @return A new {@link Statistic} for tracking the ability's activation count.
     */
    @NotNull
    public static Statistic createAbilityActivationStatistic(@NotNull NamespacedKey abilityKey, @NotNull String displayName) {
        return new SimpleStatistic(
                getAbilityActivationKey(abilityKey),
                StatisticType.LONG,
                0L,
                displayName + " Activations",
                "Times " + displayName + " has been activated"
        );
    }

    /**
     * Creates a per-skill experience {@link Statistic} definition for dynamic registration.
     * <p>
     * The generated display name and description are admin-facing metadata — see the class-level
     * javadoc for why they are not localized.
     *
     * @param skillKey    The skill's {@link NamespacedKey}.
     * @param displayName The human-readable skill name (used for the statistic display name).
     * @return A new {@link Statistic} for tracking the skill's total experience earned.
     */
    @NotNull
    public static Statistic createSkillExperienceStatistic(@NotNull NamespacedKey skillKey, @NotNull String displayName) {
        return longStat(skillKey.getKey() + "_experience",
                displayName + " Experience", "Total " + displayName + " XP earned");
    }

    /**
     * Creates a per-skill max level {@link Statistic} definition for dynamic registration.
     * <p>
     * The generated display name and description are admin-facing metadata — see the class-level
     * javadoc for why they are not localized.
     *
     * @param skillKey    The skill's {@link NamespacedKey}.
     * @param displayName The human-readable skill name (used for the statistic display name).
     * @return A new {@link Statistic} for tracking the skill's highest level reached.
     */
    @NotNull
    public static Statistic createSkillMaxLevelStatistic(@NotNull NamespacedKey skillKey, @NotNull String displayName) {
        return intStat(skillKey.getKey() + "_max_level",
                displayName + " Max Level", "Highest " + displayName + " level reached");
    }

    /**
     * Creates a {@link NamespacedKey} under the McRPG namespace. Uses the deprecated
     * {@code NamespacedKey(String, String)} constructor because these are static constants
     * initialized before a {@link org.bukkit.plugin.Plugin} instance is available.
     *
     * @param key The key portion of the {@link NamespacedKey}.
     * @return A new {@link NamespacedKey} under the McRPG namespace.
     */
    @NotNull
    @SuppressWarnings("deprecation") // NamespacedKey(String, String) — no Plugin instance in static context
    private static NamespacedKey key(@NotNull String key) {
        return new NamespacedKey(NAMESPACE, key);
    }

    /**
     * Creates a {@link StatisticType#LONG LONG} statistic with a default value of {@code 0L}
     * under the McRPG namespace.
     *
     * @param key         The key portion of the {@link NamespacedKey}.
     * @param displayName The admin-facing display name.
     * @param description The admin-facing description.
     * @return A new {@link Statistic} of type {@link StatisticType#LONG}.
     */
    @NotNull
    static Statistic longStat(@NotNull String key, @NotNull String displayName, @NotNull String description) {
        return new SimpleStatistic(key(key), StatisticType.LONG, 0L, displayName, description);
    }

    /**
     * Creates a {@link StatisticType#INT INT} statistic with a default value of {@code 0}
     * under the McRPG namespace.
     *
     * @param key         The key portion of the {@link NamespacedKey}.
     * @param displayName The admin-facing display name.
     * @param description The admin-facing description.
     * @return A new {@link Statistic} of type {@link StatisticType#INT}.
     */
    @NotNull
    static Statistic intStat(@NotNull String key, @NotNull String displayName, @NotNull String description) {
        return new SimpleStatistic(key(key), StatisticType.INT, 0, displayName, description);
    }
}
