image: java:8-jdk

stages:
  - build

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - /build/libs/*.jar
    expire_in: 1 week

after_script:
  - echo "End CI"
