config-version: 1
##################################
### Main Config For McRPG ###
##################################
configuration:
  database:
    # Sets the type of the database driver. The existing options are: 'SQLite'
    driver: SQLite
  # What worlds should McRPG be disabled in
  disabled-worlds:
    - 'test'
  # Configure the
  save-task:
    # This is how often the save task runs in seconds
    frequency: 300
  localization:
    # Language support will go in the order of user's local language -> server default -> english
    # User local language is determined by their minecraft client
    server-default-locale: en
  # Configure all admin features
  admin:
    # If enabled, admins with the permission node 'mcrpg.ability.spy' will be alerted when abilities are unlocked and upgraded
    enable-ability-spy: false
  # Modify various features for skill experience
  experience:
    # The maximum amount of damage allowed for giving experience. Any damage above this threshold will be ignored when calculating exp to award.
    max-damage-cap-to-award-exp: 100
    # The maximum amount of exp multiplier that a player should be able to get from various exp modifiers when combined.
    exp-multiplier-limit: 10.0
    # How much the experience gain should be modified if the target is blocking with a shield.
    shield-blocking-modifier: 0.5
    # Allows disabling of experience gain when taking damage from ender pearls.
    disable-experience-from-ender-pearls: true
    # Configure boosted experience from McMMO conversion
    boosted-experience:
      # When a player gains exp, this equation is factored in and if there is remaining boosted exp,
      # then it will add this equation value to the gained amount
      usage-rate: 2.25
    # Rested Experience allows players to passively gain an experience boost.
    # This experience boost is measured in Levels. So as an example, a player might have 1.2 Levels worth of Rested Experience.
    # Rested Experience is relative in terms of how much experience it multiplies as a result.
    # If a player needs 1000 experience to level up, then doubling an experience gain of 100 will consume 0.1 L=levels of Rested Experience.
    # If a player needs 10000 experience to level up, then doubling an experience gain of 100 will consume 0.01 levels of Rested Experience.
    #
    # Players can gain rested experience primarily while offline. There are configuration options to allow players to gain rested experience
    # while online as well in something called "safe zones". Safe zones are defined by hooking into other plugins such as Lands.
    # If a player logs out in a safe zone AND safe zone accumulation is enabled, then they will use the safe zone equation
    # to calculate rested experience. Otherwise, the offline equation is used.
    rested-experience:
      accumulation-rates:
        # How fast can a player accumulate rested experience while offline. Time is measured in seconds
        offline: '0.00027*time'
        # How fast can a player accumulate rested experience if allow-online-accumulation is set to ENABLED
        # and players either are not in a safe zone or safe zone accumulation is disabled. Time is measured in seconds
        online: '0.00013*time'
        # How fast can a player accumulate rested experience if they are in a safe zone and safe zones are enabled while online?
        # Time is measured in seconds
        online-safe-zone: '0.00027*time'
        # How fast can a player accumulate rested experience if they are in a safe zone and safe zones are enabled while offline?
        # Time is measured in seconds
        offline-safe-zone: '0.00056*time'
      # How long should a player have to be offline (in seconds) before they start to accumulate rested experience?
      offline-wait-period-before-accumulation: 0.0
      # What should the multiplier be when using rested experience?
      usage-rate: 3.0
      # How many levels worth of rested experience can a player have at once
      maximum-accumulation: 1.5
      # This can be ENABLED, SAFE_ZONE, or DISABLED
      # ENABLED: Allows accumulation of rested experience while online (also includes safe zones)
      # SAFE_ZONE: Only allow rested experience accumulation while online in a safe zone
      # DISABLED: Don't allow accumulation of rested experience while online
      allow-online-accumulation: SAFE_ZONE
      # If a player is marked as AFK with any afk plugin McRPG integrates with, should
      # their accumulation be disabled?
      # If there's a plugin that isn't integrated, please reach out to developers for support.
      disable-afk-accumulation: false
      # Configure the task that will give rested experience while players are online
      online-accumulator-task:
        # How often in seconds should the task run
        frequency: 30
      # Allow for faster accumulation to occur if a player is in a "safe zone"
      safe-zone:
        # Enables safe zone rested experience accumulation
        allow-safe-zone-accumulation: true
        # 3rd party plugin support for defining a safe zone.
        # If a player is standing in a location such that multiple plugins can provide a definition for a "safe zone",
        # then the final result will be the OR of all the valid plugins.
        safe-zone-hooks:
          # A WorldGuard region with the flag 'mcrpg-safe-zone' will be treated as a safe zone
          # To set this flag, use the command '/rf flag'
          world-guard:
            # If WorldGuard support should be enabled
            enabled: true
          # Allows configuring the definition of a safe zone based on different land types.
          lands:
            # If a player owns the land they are standing in, will it count as a safe zone?
            owned-lands: true
            # If a player is trusted in the land they are standing in, will it count as a safe zone?
            trusted-lands: true
            # If a player is a tenant of the land they are standing in, will it count as a safe zone?
            tenant-lands: true
            # If a player is standing in any land, will it count as a safe zone?
            any-lands: false
            # If a player is not standing in any land, will it be counted as a safe zone?
            wild-zone: false
    # Modify the exp worth of mobs from spawners and eggs
    modify-mob-spawn-experience:
      # The following format is SpawnReason: Modifier
      # The spawn reason can be selected from any in the following list
      # https://jd.papermc.io/paper/1.21.4/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
      # The modifier is how much experience gained should be multiplied by for that spawn reason.
      # Please note the above link may be for an older version of Minecraft than the one you are using,
      # make sure the version represents the version you are trying to use.
      SPAWNER: 0.5
      SPAWNER_EGG: 05
    # If when players redeem levels, should this reset the amount of exp needed to level up.
    # Ex) Player has gained 5,000 experience in Swords and uses a redeemable level. If this is enabled,
    # then the experience gained will be reset to 0 whenever the level is added. Otherwise, the 5,000 is kept.
    reset-exp-upon-redeemed-levels: true
  # Configure skill books
  skill-books:
    # If set to true, then skill books will be unable to drop in the end
    disable-books-in-end: true
  # Configure various displays (scoreboard, actionbar, and bossbar) for McRPG
  display:
    # Configure displays for whenever experience is gained
    experience-updates:
      # If set to true, players will get a visual update whenever experience is gained (unless their setting disables this)
      enabled: true
      # What type should the display be. Accepted values are: BOSSBAR or ACTIONBAR
      display-type: BOSSBAR
      # Configure additional attributes about a boss bar
      boss-bar:
        display-duration: 3
        # Can be any value found here: https://javadoc.io/doc/net.kyori/adventure-api/4.1.0/net/kyori/adventure/bossbar/BossBar.Color.html
        color: PURPLE
        # Can be any value found here: https://javadoc.io/doc/net.kyori/adventure-api/4.1.0/net/kyori/adventure/bossbar/BossBar.Overlay.html
        style: NOTCHED_10

  # Configure various gameplay mechanics
  gameplay:
    loadout:
      max-loadout-amount: 3
      max-loadout-size: 15
      loadout-display-name-response-timeout: 10
    # If enabled, players will be required to have an empty off hand in order to ready their abilities
    require-empty-off-hand-to-ready: false
    # If enabled, then a player will not be able to gain experience past a certain level.
    # An example is if we set a player to have the permission 'mcrpg.swords.500'. This player would gain no exp past level 500 in swords
    # Use mcrpg.%skill%.%level% as the perm
    enable-level-up-permissions: false

# Configure McMMO integration
mcmmo:
  # Converts a players level to exp and then convert that into 'boosted experience' using the equation below
  # To configure how boosted exp works, please look at the 'boosted-exp' section
  conversion_equation: '((skill_exp)*0.5)'