##################################
### Main Config For McMMOx ###
##################################
#
#Notes:
#    Do not use ' or " in messages as I have not yet added support for these icons.
#   - Do not remove any lines as that will throw errors
#   - This plugin only supports Minecraft color codes. Ex) &eHello World&7!
#       - Use this link for a list of the codes: https://wiki.ess3.net/mc/
#   - If you want a message to be blank, please leave it as ''
#   - This plugin supports player name place holders as %Player%
# If you receive an error when McMMOx loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
###################################
DisplayConfig:
  Scoreboard:
    DisplayName: '&5%Skill%'
    Lines:
      CurrentLevel: '&aCurrent Level:'
      CurrentExp: '&aExp:'
      ExpNeeded: '&aExp Left:'
PlayerConfiguration:
  #This amount is here for the future and currently is unused
  AmountOfTotalAbilities: 9
  #When the power level reaches a multiple of this number a point is awaded
  AbilityPointInterval: 250
  #In seconds how long should the player stay ready for
  PlayerReadyDuration: 2
Configuration:
#This is in minutes
  SaveInterval: 1
  LangFile: 'en'
  AutoUpdate: true