name: McMMOX
version: 0.0.1
author: Eunoians
description: Some description
main: us.eunoians.mcmmox.Mcmmox
api-version: 1.13
commands:
  mcmmox:
    description: Opens the main menu for McMMOX
    aliases: [mcmmo, mmo]
  mcdisplay:
    description: Allows for command based editing of display types
    aliases: [mcmmodisplay, mdisplay, mcd]
  mcadmin:
    description: Allows for admin commands
  mclink:
    description: Links a chest to a players Remote Transfer
  mcunlink:
    description: Unlinks a chest from a players Remote Transfer
  mchelp:
    description: Displays help info for commands