package us.eunoians.mcrpg.util.configuration;

import de.articdive.enum_to_yaml.interfaces.ConfigurationEnum;

import java.util.Arrays;

public enum LangEnum implements ConfigurationEnum {

    SKILL_NAMES_HEADER("SkillNames", "", "#Used for localizing skill names in GUIs and commands"),
    SKILL_NAMES_SWORDS("SkillNames.Swords", "Swords"),
    SKILL_NAMES_MINING("SkillNames.Mining", "Mining"),
    SKILL_NAMES_UNARMED("SkillNames.Unarmed", "Unarmed"),
    SKILL_NAMES_HERBALISM("SkillNames.Herbalism", "Herbalism"),
    SKILL_NAMES_ARCHERY("SkillNames.Archery", "Archery"),
    SKILL_NAMES_WOODCUTTING("SkillNames.Woodcutting", "Woodcutting"),
    SKILL_NAMES_FITNESS("SkillNames.Fitness", "Fitness"),
    SKILL_NAMES_EXCAVATION("SkillNames.Excavation", "Excavation"),
    SKILL_NAMES_AXES("SkillNames.Axes", "Axes"),
    SKILL_NAMES_FISHING("SkillNames.Fishing", "Fishing"),
    SKILL_NAMES_SORCERY("SkillNames.Sorcery", "Sorcery"),
    SKILL_NAMES_TAMING("SkillNames.Taming", "Taming"),
    SKILL_ITEM_NAMES_SWORDS("SkillItemNames.Swords", "Sword"),
    SKILL_ITEM_NAMES_MINING("SkillItemNames.Mining", "Pickaxe"),
    SKILL_ITEM_NAMES_UNARMED("SkillItemNames.Unarmed", "Fist"),
    SKILL_ITEM_NAMES_EXCAVATION("SkillItemNames.Excavation", "Shovel"),
    SKILL_ITEM_NAMES_HERBALISM("SkillItemNames.Herbalism", "Hoe"),
    SKILL_ITEM_NAMES_ARCHERY("SkillItemNames.Archery", "Bow"),
    SKILL_ITEM_NAMES_WOODCUTTING("SkillItemNames.Woodcutting", "Axe"),
    SKILL_ITEM_NAMES_AXES("SkillItemNames.Axes", "Battle Axe"),
    SKILL_ITEM_NAMES_TAMING("SkillItemNames.Taming", "Summoning Stick"),
    POWER_LINE_1("Signs.PowerLeaderboard.Line1", "&7[&6Power&7]"),
    POWER_LINE_2("Signs.PowerLeaderboard.Line2", "&b#%Rank%"),
    POWER_LINE_3("Signs.PowerLeaderboard.Line3", "&7%Player%"),
    POWER_LINE_4("Signs.PowerLeaderboard.Line4", "&7Lv. %Level%"),
    SKILL_LINE_1("Signs.SkillLeaderboard.Line1", "&7[&6%Skill%&7]"),
    SKILL_LINE_2("Signs.SkillLeaderboard.Line2", "&b#%Rank%"),
    SKILL_LINE_3("Signs.SkillLeaderboard.Line3", "&7%Player%"),
    SKILL_LINE_4("Signs.SkillLeaderboard.Line4", "&7Lv. %Level%"),
    POTION_NAMES_WATER("Potions.PotionNames.Water", "Water"),
    POTION_NAMES_AWKWARD("Potions.PotionNames.Awkward", "Awkward"),
    POTION_NAMES_HASTE("Potions.PotionNames.Haste", "Haste"),
    POTION_NAMES_MINING_FATIGUE("Potions.PotionNames.MiningFatigue", "Mining Fatigue"),
    POTION_NAMES_SPEED("Potions.PotionNames.Speed", "Speed"),
    POTION_NAMES_SLOWNESS("Potions.PotionNames.Slowness", "Slowness"),
    POTION_NAMES_JUMP("Potions.PotionNames.Jump", "Leaping"),
    POTION_NAMES_NAUSEA("Potions.PotionNames.Nausea", "Nausea"),
    POTION_NAMES_REGENERATION("Potions.PotionNames.Regeneration", "Regeneration"),
    POTION_NAMES_WATER_BREATHING("Potions.PotionNames.WaterBreathing", "Water Breathing"),
    POTION_NAMES_INVISIBILITY("Potions.PotionNames.Invisibility", "Invisibility"),
    POTION_NAMES_BLINDNESS("Potions.PotionNames.Blindness", "Blindness"),
    POTION_NAMES_NIGHT_VISION("Potions.PotionNames.NightVision", "Night Vision"),
    POTION_NAMES_HUNGER("Potions.PotionNames.Hunger", "Hunger"),
    POTION_NAMES_SATURATION("Potions.PotionNames.Saturation", "Saturation"),
    POTION_NAMES_INSTANT_HEALTH("Potions.PotionNames.InstantHealth", "Instant Health"),
    POTION_NAMES_INSTANT_DAMAGE("Potions.PotionNames.InstantDamage", "Instant Damage"),
    POTION_NAMES_WITHER("Potions.PotionNames.Wither", "Wither"),
    POTION_NAMES_HEALTH_BOOST("Potions.PotionsNames.HealthBoost", "Health Boost"),
    POTION_NAMES_ABSORPTION("Potions.PotionNames.Absorption", "Absorption"),
    POTION_NAMES_GLOWING("Potions.PotionNames.Glowing", "Glowing"),
    POTION_NAMES_LUCK("Potions.PotionNames.Luck", "Luck"),
    POTION_NAMES_UNLUCK("Potions.PotionNames.Unluck", "Unluck"),
    POTION_NAMES_DOLPHINS_GRACE("Potions.PotionNames.DolphinsGrace", "Dolphins Grace"),
    POTION_NAMES_STRENGTH("Potions.PotionNames.Strength", "Strength"),
    POTION_NAMES_WEAKNESS("Potions.PotionNames.Weakness", "Weakness"),
    POTION_NAMES_RESISTANCE("Potions.PotionNames.Resistance", "Resistance"),
    POTION_NAMES_FIRE_RESISTANCE("Potions.PotionNames.FireResistance", "Fire Resistance"),
    POTION_NAMES_LEVITATION("Potions.PotionNames.Levitation", "Levitation"),
    POTION_NAMES_SLOW_FALLING("Potions.PotionNames.SlowFalling", "Slow Falling"),
    POTION_NAMES_POISON("Potions.PotionNames.Poison", "Poison"),
    POTION_LINGERING_PREFIX("Potions.Lingering", "&fLingering", "#The translation and color code for lingering and splash potions"),
    POTION_SPLASH_PREFIX("Potions.Splash", "&fSplash"),
    POTION_NAME_PREFIX("Potions.PotionNamePrefix", "&fPotion Of %PotionName%", "#A full name would be the Splash/Lingering + the Potion Name Prefix and then replace the placeholder of %PotionName% with",
      "#the potion name defined in the configuration"),
    PLUGIN_INFO_HEADER("Messages.PluginInfo", "", "#Messages relating to the general plugin information"),
    PLUGIN_PREFIX("Messages.PluginInfo.PluginPrefix", "&7[&1McRPG&7]"),
    CUSTOM_REDEEM("Messages.CustomRedeem", "#Messages relating to redeemable experience"),
    CUSTOM_REDEEM_LISTENING("Messages.CustomRedeem.Listening", "&ePlease type in chat the amount you would like to redeem."),
    CUSTOM_REDEEM_REDEEMED_EXP("Messages.CustomRedeem.RedeemedExp", "&aYou redeemed &e%Amount% &aexp into &e%Skill%."),
    CUSTOM_REDEEM_REDEEMED_LEVELS("Messages.CustomRedeem.RedeemedLevels", "&aYou redeemed &e%Amount% &alevel(s) into &e%Skill%."),
    BLOOD_ITEM_SHATTER("Messages.Blood.ItemShatter", "&cThe Crystallized Blood was too strong and shattered the item."),
    BLOOD_APPLIED_CURSE("Messages.Blood.AppliedCurse", "&aYou have put &e%Target% under a &cBlood Curse &afor &6%Duration% &aseconds."),
    BLOOD_BEEN_CURSED("Messages.Blood.BeenCursed", "&cYou have been cursed for &6%Duration% &cseconds. You cant use any abilities during this time."),
    BLOOD_NO_LONGER_CURSED("Messages.Blood.NoLongerCursed", "&aYou are no longer cursed."),
    BLOOD_BLOOD_LORE("Messages.Blood.BloodLore", "&cBlood Buff: &7+&6%ExpBoost%&7% &cExp"),
    MISC_HEADER("Messages.Misc", "", "#Messages that dont fit anywhere"),
    MISC_SUMMONED_GUARDIAN("Messages.Misc.PoseidonsGuardianSummoned", "&cYour constant fishing has angered &bPoseidon&c. Kill his guardian for a reward."),
    MISC_GUARDIAN_NAME("Messages.Misc.PoseidonsGuardianName", "&bPoseidons Guardian"),
    MISC_CALL_OF_WILD_TOO_MANY_ENTITIES("Messages.Misc.CallOfWild.TooManyEntities", "&cThere are too many of that entity nearby to summon another."),
    SKILL_BOOKS_UPGRADED("Messages.SkillBooks.Upgraded", "&aYou upgraded %Ability% from Tier &e%OldTier% &ato &e%NewTier%&a!"),
    SKILL_BOOKS_UNLOCKED("Messages.SkillBooks.Unlocked", "&aYou unlocked &e%Ability% &aTier &e%Tier%&a!"),
    SKILL_BOOKS_INVALID_TIER("Messages.SkillBooks.InvalidTier", "&cYour ability is not currently a valid tier to use this book."),
    SKILL_BOOKS_REQUIRED_LEVEL("Messages.SkillBooks.RequiredLevel", "&cIn order to use that book, you must be level &e%Level% &cin &e%Skill%&c."),
    SKILL_BOOKS_NO_ABILITY("Messages.SkillBooks.NoAbility", "&cYou do not have that ability unlocked, thus you can not use it."),
    SKILL_BOOKS_ALREADY_UNLOCKED("Messages.SkillBooks.AlreadyUnlocked", "&cYou already have that ability unlocked."),
    ARTIFACT_CREATED("Messages.Artifacts.ArtifactCreated", "&5A &e%ArtifactType% &5artifact has been created!"),
    REDEEMABLE_EXP_ARTIFACT_USED("Messages.Artifacts.RedeemableExpArtifactUsed", "&aYou have used the artifact to gain &e%RedeemableExpAmount% &aredeemable exp."),
    ARTIFACT_SKILL_MAXED("Messages.Artifacts.SkillMaxed", "&cYou can not use that artifact because you are already at the max level for this skill."),
    SKILL_EXP_ARTIFACT_USED("Messages.Artifacts.SkillExpArtifactUsed", "&aYou have used the artifact to gain &e%SkillExpAmount% &aexp in &e%Skill%&a."),
    REDEEMABLE_LEVEL_ARTIFACT_USED("Messages.Artifacts.RedeemableLevelArtifactUsed", "&aYou have used the artifact to gain &e%RedeemableLevelAmount% &aredeemable level(s)."),
    ABILITY_POINT_ARTIFACT_USED("Messages.Artifacts.AbilityPointArtifactUsed", "&aYou have used the artifact to gain &e%AbilityPointAmount% &aability points(s)."),
    UNLOCK_BOOK_ARTIFACT_USED("Messages.Artifacts.UnlockBookArtifactUsed", "&aYou have used the artifact to gain &e%UnlockBookAmount% &aunlock books(s)."),
    UPGRADE_BOOK_ARTIFACT_USED("Messages.Artifacts.UpgradeBookArtifactUsed", "&aYou have used the artifact to gain &e%UpgradeBookAmount% &aupgrade books(s)."),
    COOLDOWN_ARTIFACT_USED("Messages.Artifacts.CooldownArtifactUsed", "&aYou have used the artifact to reset all your cooldowns."),
    MAGNET_ARTIFACT_USED("Messages.Artifacts.MagnetArtifactUsed", "&aYou have used the magnet artifact to draw in nearby items."),
    COMMANDS_HEADER("Messages.Commands", "", "#Messages used by commands"),
    COMMANDS_UTILITY_HEADER("Messages.Commands.Utility", "", "#Messages used by misc commands"),
    NO_PERMS("Messages.Commands.Utility.NoPerms", "&cYou do not have the permissions to execute that command."),
    PLAYER_HAS_NOT_LOGGED_IN("Messages.Commands.Utility.PlayerHasNotLoggedIn", "&cThat player has not logged in before."),
    PLAYER_OFFLINE("Messages.Commands.Utility.PlayerOffline", "&cThat player is offline right now."),
    INVALID_AMOUNT("Messages.Commands.Utility.InvalidAmount", "&cThe amount you entered is invalid. Please try again."),
    ONLY_PLAYERS("Messages.Commands.Utility.OnlyPlayers", "&cOnly players can run this command."),
    HELP_PROMPT("Messages.Commands.Utility.HelpPrompt", "&eUse /mchelp or /mchelp <command> for proper usage."),
    NOT_AN_INT("Messages.Commands.Utility.NotAnInt", "&cThe argument you entered is not an integer."),
    NOT_A_LONG("Messages.Commands.Utility.NotALong", "&cThe argument you entered is not a long."),
    NOT_A_SKILL("Messages.Commands.Utility.NotASkill", "&cThe argument you entered is not a valid skill."),
    NOT_AN_ABILITY("Messages.Commands.Utility.NotAnAbility", "&cThe argument you entered is not a valid ability."),
    NOT_ACTIVE_ABILITY("Messages.Commands.Utility.NotActiveAbility", "&cThe ability you entered is not an active ability."),
    NOT_ENABLED_OR_UNLOCKED("Messages.Commands.Utility.NotEnabledOrUnlocked", "&cThat ability is either disabled or you have yet to unlock it."),
    PLAYER_FOLDER_DOESNT_EXIST("Messages.Commands.Utility.PlayerFolderDoesntExist", "&cThe player folder does not exist... possibly already been converted?"),
    BEGINNING_CONVERSION("Messages.Commands.Utility.BeginningConversion", "&aYour conversion is beginning... please prevent player log in while this process is going on. There are %FileAmount% of files to process."),
    RECEIVED_REDEEMABLE_EXP("Messages.Commands.Utility.ObtainedRedeemableExp", "&aYou have received %Amount% redeemable exp. Use /mcredeem <skill> to use it!"),
    CONVERSION_COMPLETE("Messages.Commands.Utility.ConversionComplete", "&aConverted %Amount% players in %Seconds% seconds."),
    PARTY_PARTIES_DISABLED("Messages.Commands.Parties.PartiesDisabled", "&cParties are disabled for this server."),
    PARTY_NO_PENDING_INVITES("Messages.Commands.Parties.NoPendingInvites", "&cYou have no pending party invites and are not in a party."),
    PARTY_WAITING_PARTY_INVITES("Messages.Commands.Parties.WaitingPartyInvites", "&cYou have party invites waiting for you to accept using /mcparty invites."),
    PARTY_NULL_PARTY_INVITE_REMOVED("Messages.Commands.Parties.NullPartyInviteRemoved", "&cThe party you were invited to no longer exists and the invite has been removed."),
    PARTY_PENDING_PARTY_INVITE("Messages.Commands.Parties.PendingPartyInvite", "&aYou have a pending invite from &e%Party% &a. To accept, do /mcparty invites accept. To deny it and view the next invitation, do /mcparty invites deny."),
    PARTY_ALREADY_IN_PARTY("Messages.Commands.Parties.AlreadyInParty", "&cYou are already in a party."),
    PARTY_FULL_PARTY_INVITE("Messages.Commands.Parties.FullPartyInvite", "&cThe party you were invited is full."),
    PARTY_FULL_PARTY("Messages.Commands.Parties.FullParty", "&cThere are too many players in your party to invite someone else."),
    PARTY_JOINED_PARTY("Messages.Commands.Parties.PartyJoined", "&aYou joined %Party%."),
    PARTY_PLAYER_JOINED_PARTY("Messages.Commands.Parties.PlayerHasJoinedParty", "&a%Player% has joined your party!"),
    PARTY_INVITE_DECLINED("Messages.Commands.Parties.InviteDeclined", "&aYou have declined the party invite from %Party%."),
    PARTY_NOT_IN_PARTY("Messages.Commands.Parties.NotInParty", "&cYou are not in a party so you could not send an invite."),
    PARTY_IN_PARTY("Messages.Commands.Parties.InParty", "&cThat player is already in a party."),
    PARTY_NULL_PARTY("Messages.Commands.Parties.NullParty", "&cFor some reason your party does not exist so you were removed."),
    PARTY_INVITED_PLAYER("Messages.Commands.Parties.InvitedPlayer", "&aYou have invited the player successfully!"),
    PARTY_BEEN_INVITED("Messages.Commands.Parties.BeenInvited", "&aYou have been invited by &e%Player% &ato their party! To join do &e/mcparty invites accept."),
    PARTY_ISSUE_INVITING("Messages.Commands.Parties.IssueInviting", "&cThere was an issue inviting that player. Please wait a few seconds and try again."),
    PARTY_NO_INVITE_PERMISSION("Messages.Commands.Parties.NoInvitePermission", "&cYou do not have permission to invite people to your party."),
    PARTY_PLAYER_OFFLINE("Messages.Commands.Parties.PlayerOffline", "&cThat player is not currently online."),
    PARTY_PARTY_NAME_IN_USE("Messages.Commands.Parties.PartyNameInUse", "&cThat name is already in use, please use another."),
    PARTY_INVALID_PARTY_NAME("Messages.Commands.Parties.InvalidPartyName", "&cYour party name contains an invalid string and could not be accepted."),
    PARTY_PARTY_CREATED("Messages.Commands.Parties.PartyCreated", "&aYou have successfully created the %Party% party."),
    PARTY_CANT_KICK_SELF("Messages.Commands.Parties.CantKickSelf", "&cYou can not kick yourself from the party."),
    PARTY_CANT_KICK_PLAYER("Messages.Commands.Parties.CantKickPlayer", "&cYou can not kick people at the same rank or higher than you."),
    PARTY_ISSUE_KICKING("Messages.Commands.Parties.IssueKicking", "&cThere was an issue with kicking that player from your party."),
    PARTY_KICKED_PLAYER("Messages.Commands.Parties.KickedPlayer", "&aYou have kicked %Player% from your party."),
    PARTY_KICKED_FROM_PARTY("Messages.Commands.Parties.KickedFromParty", "&cYou have been kicked from %Party%."),
    PARTY_NO_KICK_PERMS("Messages.Commands.Parties.NoKickPermissions", "&cYou do not have permission to kick people from your party."),
    PARTY_CANT_DISBAND("Messages.Commands.Parties.CantDisband", "&cOnly party owners can disband the party."),
    PARTY_PARTY_WAS_DISBANDED("Messages.Commands.Parties.PartyWasDisbanded", "&cYour party was disbanded."),
    PARTY_DISBANDED_PARTY("Messages.Commands.Parties.DisbandedParty", "&aYou have disbanded your party."),
    PARTY_LEFT_PARTY("Messages.Commands.Parties.LeftParty", "&aYou have left your party."),
    PARTY_PLAYER_LEFT_PARTY("Messages.Commands.Parties.PlayerLeftParty", "&c%Player% has left your party."),
    PARTY_CANT_PROMOTE_SELF("Messages.Commands.Parties.CantSelfPromote", "&cYou can not promote yourself."),
    PARTY_CANT_PROMOTE_MOD("Messages.Commands.Parties.CantPromoteMod", "&cYou can not promote a mod to owner. Use the /mcparty setowner command instead."),
    PARTY_PROMOTED_PLAYER("Messages.Commands.Parties.PromotedPlayer", "&aYou have promoted %Player% to mod!"),
    PARTY_BEEN_PROMOTED("Messages.Commands.Parties.BeenPromoted", "&aYou have been promoted to a party moderator!"),
    PARTY_PLAYER_NOT_IN_PARTY("Messages.Commands.Parties.PlayerNotInParty", "&cThat player is not in your party."),
    PARTY_CANT_PROMOTE("Messages.Commands.Parties.CantPromote", "&cOnly party owners can promote players."),
    PARTY_CANT_DEMOTE_SELF("Messages.Commands.Parties.CantSelfDemote", "&cOnly party owners can demote players."),
    PARTY_CANT_DEMOTE_MEMBER("Messages.Commands.Parties.CantDemoteMember", "&cYou can not demote a member."),
    PARTY_DEMOTED_PLAYER("Messages.Commands.Parties.DemotedPlayer", "&aYou have demoted %Player%!"),
    PARTY_BEEN_DEMOTED("Messages.Commands.Parties.BeenDemoted", "&cYou have been demoted by your party owner!"),
    PARTY_CANT_DEMOTE("Messages.Commands.Parties.CantDemote", "&cOnly party owners can demote players."),
    PARTY_SET_PLAYER_OWNER("Messages.Commands.Parties.SetPlayerOwner", "&aYou have promoted %Player% to party owner!"),
    PARTY_BEEN_SET_OWNER("Messages.Commands.Parties.BeenSetOwner", "&aYou have been set as your partys owner!"),
    PARTY_CANT_ACCESS_BANK("Messages.Commands.Parties.CantAccessBank", "&cOnly members with the role of %Bank_Role%+ can use the private bank."),
    PARTY_CANT_EDIT_ROLES("Messages.Commands.Parties.CantEditRoles", "&cOnly owners can edit roles."),
    PARTY_CHAT_ENABLED("Messages.Commands.Parties.PartyChatEnabled", "&aParty chat was enabled."),
    PARTY_CHAT_DISABLED("Messages.Commands.Parties.PartyChatDisabled", "&cParty chat was disabled."),
    PARTY_REQUESTED_TPAHERE("Messages.Commands.Parties.RequestedTpahere", "&eYou have requested %Player% to teleport to you."),
    PARTY_RECEIVED_TPAHERE_REQUEST("Messages.Commands.Parties.ReceivedTpahereRequest", "&eYou have been requested to teleport to %Player%. Do /mcparty tpaccept to accept."),
    PARTY_REQUESTED_TPA("Messages.Commands.Parties.RequestedTpa", "&eYou have requested to teleport to %Player%."),
    PARTY_RECEIVED_TPA_REQUEST("Messages.Commands.Parties.ReceivedTpaRequest", "&eYou have been requested to have %Player% teleport to you. Do /mcparty tpaccept to accept."),
    PARTY_TP_WAS_AUTO_ACCEPTED("Messages.Commands.Parties.TpWasAutoAccepted", "&aYour settings auto accepted a tp request."),
    PARTY_TP_REQUEST_AUTO_ACCEPTED("Messages.Commands.Parties.TpRequestAutoAccepted", "&aYour request was automatically accepted."),
    PARTY_NO_PENDING_TELEPORT_REQUESTS("Messages.Commands.Parties.NoPendingTeleportRequests", "&cThere are no pending teleport requests."),
    PARTY_ISSUE_ACCEPTING_REQUEST("Messages.Commands.Parties.IssueAcceptingRequest", "&cThere was an issue accepting the request."),
    PARTY_PLAYER_DID_NOT_REQUEST("Messages.Commands.Parties.PlayerDidNotRequest", "&cThat player did not give you a request."),
    PARTY_CANT_RENAME("Messages.Commands.Parties.CantRename", "&cOnly owners can rename the party."),
    PARTY_RENAMED_PARTY("Messages.Commands.Parties.RenamedParty", "&aYour party name was successfully changed."),
    PARTY_TP_ACCEPTED("Messages.Commands.Parties.TpAccepted", "&aAccepted teleport request..."),
    PARTY_TP_ACCEPTED_AND_STAND_STILL("Messages.Commands.Parties.TpAcceptedAndStandStill", "&eAccepted teleport request... Please stand still for 5 seconds..."),
    PARTY_TP_WAS_ACCEPTED("Messages.Commands.Parties.TpWasAccepted", "&a%Player% accepted your request."),
    PARTY_TP_WAS_ACCEPTED_AND_STAND_STILL("Messages.Commands.Parties.TpWasAcceptedAndStandStill", "&e%Player% accepted your request. Please stand still for 5 seconds..."),
    PARTY_TELEPORTATION_WAS_CANCELED("Messages.Commands.Parties.TeleportationCanceled", "&cThe teleportation request has been cancelled."),
    PARTY_WAS_FORCE_DISBANDED("Messages.Commands.Parties.PartyWasForceDisbanded", "&cYour party was disbanded."),
    PARTY_FORCE_DISBANDED_PARTY("Messages.Commands.Parties.ForceDisbandedParty", "&aYou have forcibly disbanded the party."),
    PARTY_PLAYER_NOT_HAVE_PARTY("Messages.Commands.Parties.PlayerNotHaveParty", "&cThat player does not have a party."),
    PARTY_FORCE_KICKED_FROM_PARTY("Messages.Commands.Parties.ForceKickedFromParty", "&cYou were forcibly kicked from your party."),
    PARTY_FORCE_KICKED_PLAYER("Messages.Commands.Parties.ForceKickedPlayer", "&aYou have force kicked %Player% from their party."),
    PARTY_FORCE_SET_OWNER_FROM_PARTY("Messages.Commands.Parties.ForceSetOwnerFromParty", "&aYou were set as the owner of your party."),
    PARTY_FORCE_SET_OWNER("Messages.Commands.Parties.ForceSetOwner", "&aYou have set %Player% to be the owner of their party."),
    PARTY_OWNER_FORCIBLY_SET("Messages.Commands.Parties.PartyOwnerForciblySet", "&cA new party owner has forcibly been set."),
    PARTY_FORCE_SET_PARTY_NAME("Messages.Commands.Parties.ForceSetPartyName", "&aYou have renamed &e%Player%s &aparty to &5%Name%."),
    PARTY_PARTY_EXP_INVALID("Messages.Commands.Parties.PartyExpInvalid", "&cExp must be greater than 0."),
    PARTY_PARTY_LEVELS_INVALID("Messages.Commands.Parties.PartyLevelsInvalid", "&cLevels must be greater than 0."),
    PARTY_PARTY_EXP_GIVEN("Messages.Commands.Parties.PartyExpGiven", "&aYou have given &e%Exp% &aexp to &e%Player%s &aparty."),
    PARTY_PARTY_LEVELS_GIVEN("Messages.Commands.Parties.PartyLevelsGiven", "&aYou have given &e%Levels% &alevels to &e%Player%s &aparty."),
    PARTY_NO_UPGRADE_PERMISSIONS("Messages.Commands.Parties.NoUpgradePermission", "&cYou do not have permission to upgrade your party."),
    PARTY_PARTY_UPGRADED("Messages.Commands.Parties.PartyUpgraded", "&a%Player% has upgraded %Upgrade% to level %Level%!"),
    RELOADED_FILES("Messages.Commands.ReloadFiles", "&aYou have successfully reloaded all files for this plugin."),
    MCHELP_ERROR("Messages.Commands.McHelp.Error", "&cPlease type /mchelp <command> <page> for usage. Please note all commands may not have help messages."),
    MCHELP_DEFAULT("Messages.Commands.McHelp.Default", Arrays.asList("&e--------------------------", "&7[&6McRPG Command &7]&3 /mcrpg",
            "&3    -Opens main McRPG gui", "&7[&6McDisplay Command&7]&3 /mchelp mcdisplay", "&3    -Help prompt for mcdisplay.",
            "&7[&6McAdmin Command &7]&3 /mchelp mcadmin", "&3    -Help prompt for mcadmin.", "&e--------------------------")),
    WORLDGUARD_INVALID_ACTION("Messages.WorldGuard.InvalidActionType", "&cThere is a faulty action type in your config... canceling initiation of %path%"),
    WORLDGUARD_INVALID_MATERIAL("Messages.WorldGuard.InvalidMaterial", "&cYou provided a faulty material in your config... canceling initiation of %path%"),
    WORLDGUARD_INVALID_ENTITY("Messages.WorldGuard.InvalidEntity", "&cYou provided a faulty entity in your config... canceling initiation of %path%"),
    WORLDGUARD_INVALID_SKILL("Messages.WorldGuard.InvalidSkillParameter", "&cYou provided a faulty skill parameter in your config... canceling initiation of %path%"),
    WORLDGUARD_INVALID_ABILITY("Messages.WorldGuard.InvalidAbilityParameter", "&cYou provided a faulty ability parameter in your config... canceling initiation of %path%"),
    MCHELP_MCDISPLAY("Messages.Commands.McHelp.McDisplay", Arrays.asList("&e--------------------------", "&7[&6McDisplay Command&7]&3 /mcdisplay {Skill}",
            "&3    -Opens your display for the skill.", "&7[&6McDisplay Command &7]&3 /mcdisplay clear", "&3    -Clears display.",
            "&e--------------------------")),
    MCHELP_MCADMIN1("Messages.Commands.McHelp.McAdmin1", Arrays.asList("&e--------------------------",
            "&7[&6AbilityPoints Give Command&7]&3 /mcadmin give abilitypoints {Player} {Amount}", "&3    -Opens your display for the skill.",
            "&7[&6Exp Give Command&7]&3 /mcadmin give exp {Player} {Amount} {Skill}", "&3    -Give a player exp in a skill.",
            "&7[&6Level Give Command&7]&3 /mcadmin give level {Player} {Amount} {Skill}", "&3    -Give a player levels in a skill.",
            "&7[&6Ability Give Command&7]&3 /mcadmin give ability {Player} {Ability}", "&3    -Give a player an ability.",
            "&7[&6Ability Replace Command&7]&3 /mcadmin replace {Player} {Ability} {Ability}", "&3    -Replace an ability with another.",
            "&eDo /mchelp mcadmin 2 for more.", "&e--------------------------")),
    MCHELP_MCADMIN2("Messages.Commands.McHelp.McAdmin2", Arrays.asList("&e--------------------------",
            "&7[&6Ability Remove Command&7]&3 /mcadmin remove {Player} {Ability}", "&3    -Removes an ability from a player.",
            "&7[&6View Loadout Command&7]&3 /mcadmin view loadout {Player}", "&3    -Views a players ability loadout.",
            "&7[&6View Skill Command&7]&3 /mcadmin view {Skill} {Player}", "&3    -View information about a players skill.",
            "&7[&6Cooldown Set Command&7]&3 /mcadmin cooldown set {Player} {Ability} {Duration}", "&3    -Sets a players cooldown for an ability.",
            "&7[&6Cooldown Remove Command&7]&3 /mcadmin cooldown remove {Player} {Ability}", "&3    -Removes a players cooldown for an ability.",
            "&eDo /mchelp mcadmin 3 for more.", "&e--------------------------")),
    MCHELP_MCADMIN3("Messages.Commands.McHelp.McAdmin3", Arrays.asList("&e--------------------------",
            "&7[&6Cooldown Add Command&7]&3 /mcadmin cooldown add {Player} {Ability} {Duration}", "&3    -Adds time to a players cooldown for an ability.",
            "&7[&6Reset Skill Command&7]&3 /mcadmin reset skill {Player} {Skill}", "&3    -Resets a players skill.",
            "&7[&6Reset Ability Command&7]&3 /mcadmin reset ability {Player} {Ability}", "&3    -Resets a players ability",
            "&7[&6Reset Player Command&7]&3 /mcadmin reset player {Player}", "&3    -Resets a player.", "&eDo /mchelp mcadmin 4 for more", "&e--------------------------")),
    MCHELP_MCADMIN4("Messages.Commands.McHelp.McAdmin4", Arrays.asList("&e--------------------------", "&7[&6Redeemable Exp Give Command&7]&3 /mcadmin give exp {Player} {Amount}",
            "&3    -Gives redeemable exp", "&7[&6Redeemable Level Give Command&7]&3 /mcadmin give level {Player} {Amount}", "&3    -Gives redeemable levels", "&7[&6Upgrade Book Give Command&7]&3 /mcadmin give book upgrade {Player}",
            "&3    -Give a player an upgrade book", "&7[&6Unlock Book Give Command&7]&3 /mcadmin give book unlock {Player}", "&3    -Give a player an upgrade book", "&e--------------------------")),
    MCHELP_MCPARTY1("Messages.Commands.McHelp.McParty1", Arrays.asList("&e--------------------------",
      "&7[&6Party GUI&7]&3 /mcparty", "&3    -Opens the main party GUI", "&7[&6Create Party&7]&3 /mcparty create %name%", "&3    -Creates a party with given name",
      "&7[&6Invite Player&7]&3 /mcparty invite %Player%", "&3    -Invites player to party", "&7[&6Accept Invite&7]&3 /mcparty invites accept", "&3    -Accepts the party invite",
      "&7[&6Deny Invite&7]&3 /mcparty invites deny", "&3    -Denys the party invite", "&eDo /mchelp mcparty 2 for more", "&e--------------------------")),
    MCHELP_MCPARTY2("Messages.Commands.McHelp.McParty2", Arrays.asList("&e--------------------------",
      "&7[&6Chat Command&7]&3 /mcparty chat", "&3    -Toggles party chat mode", "&7[&6TP Command&7]&3 /mcparty tpa %Player%", "&3    -Requests to tp to a party member",
      "&7[&6TPHere Command&7]&3 /mcparty tpahere %Player%", "&3    -Requests a party member to tp to you", "&7[&6TPAccept Command&7]&3 /mcparty tpaccept",
      "&3    -Accepts the incoming teleport request", "&eDo /mchelp mcparty 3 for more", "&e--------------------------")),
    MCHELP_MCPARTY3("Messages.Commands.McHelp.McParty3", Arrays.asList("&e--------------------------",
      "&7[&6Storage Command&7]&3 /mcparty storage", "&3    -Access the private bank", "&7[&6Roles GUI&7]&3 /mcparty roles", "&3    -Opens the roles gui",
      "&7[&6Kick Player&7]&3 /mcparty kick %Player%", "&3    -Kicks player from the party", "&7[&6Disband Party&7]&3 /mcparty disband", "&3    -Disbands the party",
      "&eDo /mchelp mcparty 4 for more", "&e--------------------------")),
    MCHELP_MCPARTY4("Messages.Commands.McHelp.McParty4", Arrays.asList("&e--------------------------",
      "&7[&6Promote Command&7]&3 /mcparty promote %Player%", "&3    -Promotes player to mod", "&7[&6Demote Command&7]&3 /mcparty demote %Player%",
      "&3    -Demotes player from mod", "&7[&6Set Owner Command&7]&3 /mcparty setowner %Player%", "&3    -Sets player to owner in the party", "&7[&6Rename Command&7]&3 /mcparty rename %name%",
      "&3    -Renames the party", "&e--------------------------")),
    MCHELP_MCEXP("Messages.Commands.McHelp.McExp", Arrays.asList("&e--------------------------",
      "&7[&6View Command&7]&3 /mcexp %Skill%", "&3    -View exp sources for a skill", "&e--------------------------")),
    MCDISPLAY_INVALID_INPUT("Messages.Commands.McDisplay.InvalidInput", "&c%String% is not a skill or display type.", "#%String% is the failed input"),
    MCDISPLAY_NOT_A_TYPE("Messages.Commands.McDisplay.NotAType", "&c%String% is not a proper display type. Use bossbar, actionbar or scoreboard."),
    MCDISPLAY_NOTHING_TO_CLEAR("Messages.Commands.McDisplay.NothingToClear", "&cThere is nothing to remove."),
    MCADMIN_GIVE_ABILITY_POINTS("Messages.Commands.Admin.Give.AbilityPoints", "&aYou gave %Player% &e%Amount% &aability points."),
    MCADMIN_GIVE_EXP("Messages.Commands.Admin.Give.Exp", "&aYou gave %Player% &e%Amount% &aexp in &5%Skill%."),
    MCADMIN_GIVE_LEVEL("Messages.Commands.Admin.Give.Level", "&aYou gave %Player% &e%Amount% &alevel(s) in &5%Skill%."),
    MCADMIN_GIVE_REDEEMABLE_EXP("Messages.Commands.Admin.Give.RedeemableExp", "&aYou gave %Player% %Amount% redeemable exp."),
    MCADMIN_GIVE_REDEEMABLE_LEVELS("Messages.Commands.Admin.Give.RedeemableLevels", "&aYou gave %Player% %Amount% redeemable levels."),
    MCADMIN_GIVE_ABILITY("Messages.Commands.Admin.Give.Ability", "&aYou gave %Player% &5%Ability%."),
    MCADMIN_GIVE_LOADOUT_FULL("Messages.Commands.Admin.Give.LoadoutFull", "&cThe players ability loadout is full."),
    MCADMIN_GIVE_DOES_NOT_HAVE_ABILITY("Messages.Commands.Admin.Give.DoesNotHaveAbility", "&cThe player does not have %Ability%."),
    MCADMIN_GIVE_REPLACED("Messages.Commands.Admin.Give.Replaced", "&aYou replaced %Player%s %Old_Ability% with %New_Ability%."),
    MCADMIN_GIVE_ALREADY_HAVE("Messages.Commands.Admin.Give.AlreadyHave", "&cThe player already has that ability."),
    MCADMIN_GIVE_HAS_ACTIVE("Messages.Commands.Admin.Give.HasActive", "&cThe player already has an active ability for that skill."),
    MCADMIN_GIVE_BOOK("Messages.Commands.Admin.Give.Book", "&aYou gave %Player% an %Type% book."),
    MCADMIN_RECEIVE_ABILITY_POINTS("Messages.Commands.Admin.Receive.AbilityPoints", "&aYou were given &e%Amount% &aability points."),
    MCADMIN_RECEIVE_EXP("Messages.Commands.Admin.Receive.Exp", "&aYou were given &e%Amount% &aexp in &5%Skill%."),
    MCADMIN_RECEIVE_LEVEL("Messages.Commands.Admin.Receive.Level", "&aYou were given &e%Amount% &alevel(s) in &5%Skill%."),
    MCADMIN_RECEIVE_REDEEMABLE_EXP("Messages.Commands.Admin.Receive.RedeemableExp", "&aYou received %Amount% redeemable exp. Use /mcredeem {Skill} to use"),
    MCADMIN_RECEIVE_REDEEMABLE_LEVELS("Messages.Commands.Admin.Receive.RedeemableLevels", "&aYou received %Amount% redeemable levels. Use /mcredeem {Skill} to us."),
    MCADMIN_RECEIVE_ABILITY("Messages.Commands.Admin.Receive.Ability", "&aYou were given &5%Ability%."),
    MCADMIN_RECEIVE_REPLACED("Messages.Commands.Admin.Receive.Replaced", "&aYour %Old_Ability% was replaced with %New_Ability%."),
    MCADMIN_RECEIVE_BOOK("Messages.Commands.Admin.Receive.Book", "&aYou were given an %Type% book."),
    MCADMIN_REMOVE_ABILITY("Messages.Commands.Admin.Remove.Ability", "Ability: '&aYou removed &5%Ability% &afrom %Player%s loadout."),
    MCADMIN_REMOVED_ABILITY("Messages.Commands.Admin.Removed.Ability", "&5%Ability% &cwas removed from your loadout."),
    MCADMIN_COOLDOWN_SET("Messages.Commands.Admin.Cooldown.Set", "&aYou set %Player%s &5%Ability% &ato have a &e%Cooldown% &asecond cooldown."),
    MCADMIN_COOLDOWN_WAS_SET("Messages.Commands.Admin.Cooldown.WasSet", "&cYour &5%Ability% &cnow has a &e%Cooldown% &csecond cooldown."),
    MCADMIN_COOLDOWN_REMOVE("Messages.Commands.Admin.Cooldown.Remove", "&aYou removed %Player%s cooldown for &5%Ability%."),
    MCADMIN_COOLDOWN_REMOVED("Messages.Commands.Admin.Cooldown.Removed", "&aYour cooldown for &5%Ability% &awas removed."),
    MCADMIN_COOLDOWN_REPLACE_REMOVE("Messages.Commands.Admin.Cooldown.ReplaceRemove", "&aYou removed %Player%s replace cooldown."),
    MCADMIN_COOLDOWN_REPLACE_REMOVED("Messages.Commands.Admin.Cooldown.ReplaceRemoved", "&aYour cooldown for replacing abilities has been removed."),
    MCADMIN_COOLDOWN_NO_REPLACE_COOLDOWN("Messages.Commands.Admin.Cooldown.NoReplaceCooldown", "&cThat player doesnt have a replace cooldown."),
    MCADMIN_COOLDOWN_ADD("Messages.Commands.Admin.Cooldown.Add", "&aYou added &e%Cooldown% &aseconds to %Player%s cooldown for &5%Ability%."),
    MCADMIN_COOLDOWN_ADDED("Messages.Commands.Admin.Cooldown.Added", "&cYour cooldown for &5%Ability% %chas &e%Cooldown% &cseconds added to it."),
    MCADMIN_RESET_SKILL_WAS_RESET("Messages.Commands.Admin.Reset.SkillWasReset", "&cYour %Skill% skill was reset."),
    MCADMIN_RESET_SKILL_RESET("Messages.Commands.Admin.Reset.SkillReset", "&aYou reset %Player%s %Skill% skill."),
    MCADMIN_RESET_ABILITY_WAS_RESET("Messages.Commands.Admin.Reset.AbilityWasReset", "&cYour %Ability% ability was reset."),
    MCADMIN_RESET_ABILITY_RESET("Messages.Commands.Admin.Reset.AbilityReset", "&aYou reset %Player%s %Ability% ability."),
    MCADMIN_RESET_PLAYER_WAS_RESET("Messages.Commands.Admin.Reset.PlayerWasReset", "&cYour McRPG stats were reset."),
    MCADMIN_RESET_PLAYER_RESET("Messages.Commands.Admin.Reset.PlayerReset", "&aYou reset %Player%s McRPG stats."),
    MCADMIN_ABILITY_SPY_UNLOCK("Messages.Commands.Admin.AbilitySpy.Unlock", "&a%Player% unlocked %Ability%"),
    MCADMIN_ABILITY_SPY_UPGRADE("Messages.Commands.Admin.AbilitySpy.Upgrade", "&a%Player% upgraded %Ability% to tier %Tier%"),
    ABILITIES_BLEED_PLAYER_BLEEDING("Messages.Abilities.Bleed.PlayerBleeding", "&cYou are now bleeding."),
    ABILITIES_BLEED_PLAYER_BLEEDING_STOPPED("Messages.Abilities.Bleed.BleedingStopped", "&cThe bleeding has stopped."),
    ABILITIES_RAGE_SPIKE_CHARGING("Messages.Abilities.RageSpike.Charging", "&eYou are now charging Rage Spike. Please stay crouched for &a%Charge% &eseconds."),
    ABILITIES_RAGE_SPIKE_CHARGE_CANCELLED("Messages.Abilities.RageSpike.ChargeCancelled", "&cYou canceled the charge of Rage Spike."),
    ABILITIES_SERRATED_STRIKES_ACTIVATED("Messages.Abilities.SerratedStrikes.Activated", "&aSerrated Strikes is now active."),
    ABILITIES_SERRATED_STRIKES_DEACTIVATED("Messages.Abilities.SerratedStrikes.Deactivated", "&cSerrated Strikes has deactivated."),
    ABILITIES_TAINTED_BLADE_ACTIVATED("Messages.Abilities.TaintedBlade.Activated", "&aTainted Blade has activated."),
    ABILITIES_REMOTE_TRANSFER_FAILED_LINK("Messages.Abilities.RemoteTransfer.FailedLink", "&cYou are unable to link to that chest."),
    ABILITIES_REMOTE_TRANSFER_NOT_A_CHEST("Messages.Abilities.RemoteTransfer.NotAChest", "&cYou must be looking at a chest for this command to work."),
    ABILITIES_REMOTE_TRANSFER_LINKED("Messages.Abilities.RemoteTransfer.Linked", "&aYou have successfully linked a chest."),
    ABILITIES_REMOTE_TRANSFER_UNLINKED("Messages.Abilities.RemoteTransfer.Unlinked", "&aYou have unlinked your chest."),
    ABILITIES_REMOTE_TRANSFER_IS_LINKED("Messages.Abilities.RemoteTransfer.IsLinked", "&cThat chest is currently linked to %Player%."),
    ABILITIES_REMOTE_TRANSFER_IS_NOT_LINKED("Messages.Abilities.RemoteTransfer.IsNotLinked", "&cYou are not linked to a chest."),
    ABILITIES_REMOTE_TRANSFER_ADMIN_UNLINKED("Messages.Abilities.RemoteTransfer.AdminUnlinked", "&cSomeone has unlinked your chest."),
    ABILITIES_REMOTE_TRANSFER_CHEST_MISSING("Messages.Abilities.RemoteTransfer.ChestMissing", "&cFor some reason your chest is missing... Delinking..."),
    ABILITIES_SUPER_BREAKER_ACTIVATED("Messages.Abilities.SuperBreaker.Activated", "&aSuper breaker is now active."),
    ABILITIES_SUPER_BREAK_DEACTIVATED("Messages.Abilities.SuperBreaker.Deactivated", "&cSuper breaker has deactivated."),
    ABILITIES_ORE_SCANNED_NOTHING_FOUND("Messages.Abilities.OreScanner.NothingFound", "&cNo ores were found in your scan."),
    ABILITIES_ORE_SCANNER_POINTING_TO_VALUABLE("Messages.Abilities.OreScanner.PointingToValuable", "&cYou are now looking towards the most valuable ore."),
    ABILITIES_ORE_SCANNER_DIAMONDS_FOUND("Messages.Abilities.OreScanner.DiamondsFound", "&aYour scan showed &e%Amount% &adiamond ore near you."),
    ABILITIES_ORE_SCANNER_EMERALDS_FOUND("Messages.Abilities.OreScanner.EmeraldsFound", "&aYour scan showed &e%Amount% &aemerald ore near you."),
    ABILITIES_ORE_SCANNER_GOLD_FOUND("Messages.Abilities.OreScanner.GoldFound", "&aYour scan showed &e%Amount% &agold ore near you."),
    ABILITIES_STICKY_FINGERS_RESISTED("Messages.Abilities.StickyFingers.Resisted", "&aYou resisted being disarm."),
    ABILITIES_DISARM_PLAYER_DISARMED("Messages.Abilities.Disarm.PlayerDisarmed", "&aYou disarmed %Player%."),
    ABILITIES_DISARM_BEEN_DISARMED("Messages.Abilities.Disarm.BeenDisarmed", "&cYou have been disarmed."),
    ABILITIES_BERSERK_ACTIVATED("Messages.Abilities.Berserk.Activated", "&aBerserk is now active."),
    ABILITIES_BERSERK_DEACTIVATED("Messages.Abilities.Berserk.Deactivated", "&cBerserk has deactivated."),
    ABILITIES_SMITING_FIST_ACTIVATED("Messages.Abilities.SmitingFist.Activated", "&aSmiting Fist is now active."),
    ABILITIES_SMITING_FIST_DEACTIVATED("Messages.Abilities.SmitingFist.Deactivated", "&cSmiting Fist has deactivated."),
    ABILITIES_SMITING_FIST_SMITED("Messages.Abilities.SmitingFist.Smited", "&aYou smited %Player%."),
    ABILITIES_DENSE_IMPACT_ACTIVATED("Messages.Abilities.DenseImpact.Activated", "&aDense Impact is now active."),
    ABILITIES_DENSE_IMPACT_DEACTIVATED("Messages.Abilities.DenseImpact.Deactivated", "&cDense Impact has deactivated."),
    ABILITIES_MASS_HARVEST_ACTIVATED("Messages.Abilities.MassHarvest.Activated", "&aMass Harvest has activated."),
    ABILITIES_PANS_BLESSING_ACTIVATED("Messages.Abilities.PansBlessing.Activated", "&aPans Blessing has activated."),
    ABILITIES_BLESSING_OF_ARTEMIS_ACTIVATED("Messages.Abilities.BlessingOfArtemis.Activated", "&aThe goddess of the hunt has blessed you with invisibility young hunter."),
    ABILITIES_BLESSING_OF_ARTEMIS_HIT("Messages.Abilities.BlessingOfArtemis.Hit", "&cA blessed hunter has struck you."),
    ABILITIES_BLESSING_OF_APOLLO_ACTIVATED("Messages.Abilities.BlessingOfApollo.Activated", "&aThe sun god has blessed you with his fiery power."),
    ABILITIES_BLESSING_OF_APOLLO_HIT("Messages.Abilities.BlessingOfApollo.Hit", "&cThe power of the sun god has struck you."),
    ABILITIES_CURSE_OF_HADES_ACTIVATED("Messages.Abilities.CurseOfHades.Activated", "&aThe god of the dead has cursed your arrow with hells power."),
    ABILITIES_CURSE_OF_HADES_HIT("Messages.Abilities.CurseOfHades.Hit", "&cThe power of hell has entered your body."),
    ABILITIES_DAZE_HIT("Messages.Abilities.Daze.Hit", "&cThe sudden strike of the arrow has left you confused."),
    ABILITIES_TIPPED_ARROWS_HIT("Messages.Abilities.TippedArrows.Hit", "&cYou were stuck with a potion tipped arrow."),
    ABILITIES_PUNCTURE_HIT("Messages.Abilities.Puncture.Hit", "&cYour lungs were punctured and you are now Bleeding."),
    ABILITIES_COMBO_HIT("Messages.Abilities.Combo.Hit", "&cBeing hit by a combo has dealt extra damage to you."),
    ABILITIES_DEMETERS_SHRINE_ACTIVATED("Messages.Abilities.DemetersShrine.Activated", "&aReceive &e%Multiplier% exp &afor &e%Duration% minutes on all collection skills."),
    ABILITIES_DEMETERS_SHRINE_ON_COOLDOWN("Messages.Abilities.DemetersShrine.StillOnCooldown", "&aYour Demeters Shrine is still on cooldown!"),
    ABILITIES_TEMPORAL_HARVEST_ACTIVATED("Messages.Abilities.TemporalHarvest.Activated", "&aYour axe cuts through time, harvesting the saplings future."),
    ABILITIES_HESPERIDES_APPLES_ACTIVATED("Messages.Abilities.HesperidesApples.Activated", "&aThe apple you ate still contained bits of power from Hesperides Garden. It will be a bit before you can handle it again."),
    ABILITIES_ROLL_ACTIVATED("Messages.Abilities.Roll.Activated", "&aYou managed to roll, negating some of your fall damage."),
    ABILITIES_BULLET_PROOF_ACTIVATED("Messages.Abilities.BulletProof.Activated", "&aYou managed to negate the projectile."),
    ABILITIES_DODGE_ACTIVATED("Messages.Abilities.Dodge.Activated", "&aYou dodged your opponents attack."),
    ABILITIES_DIVINE_ESCAPE_ACTIVATED("Messages.Abilities.DivineEscape.Activated", "&aYou managed to escape with divine power. McRPG exp gain will be debuffed by &c%Exp_Debuff%% &aand you will take &c%Damage_Debuff%% &aextra damage for a while."),
    ABILITIES_DIVINE_ESCAPE_EXP_EXPIRE("Messages.Abilities.DivineEscape.ExpDebuffExpire", "&aYour Divine Escape exp debuff has expired."),
    ABILITIES_DIVINE_ESCAPE_DAMAGE_EXPIRE("Messages.Abilities.DivineEscape.DamageDebuffExpire", "&aYour Divine Escape damage debuff has expired."),
    ABILITIES_FRENZY_DIG_ACTIVATED("Messages.Abilities.FrenzyDig.Activated", "&aFrenzy Dig has been activated!"),
    ABILITIES_FRENZY_DIG_DEACTIVATED("Messages.Abilities.FrenzyDig.Deactivated", "&cFrenzy Dig has deactivated!"),
    ABILITIES_HAND_DIGGING_ACTIVATED("Messages.Abilities.HandDigging.Activated", "&aHand Digging has been activated!"),
    ABILITIES_HAND_DIGGING_DEACTIVATED("Messages.Abilities.HandDigging.Deactivated", "&cHand Digging has deactivated!"),
    ABILITIES_PANS_SHRINE_ACTIVATED("Messages.Abilities.PansShrine.Activated", "&aPan has used the power of nature to change the surrounding landscape!"),
    ABILITIES_PANS_SHRINE_ON_COOLDOWN("Messages.Abilities.PansShrine.StillOnCooldown", "&aYour Pans Shrine is still on cooldown!"),
    ABILITIES_CRIPPLING_BLOW_ACTIVATED("Messages.Abilities.CripplingBlow.Activated", "&aCrippling Blow is now active! Strike enemies to cripple them with debuffs!"),
    ABILITIES_CRIPPLING_BLOW_HIT("Messages.Abilities.CripplingBlow.Hit", "&cYou been struck with a crippling blow!"),
    ABILITIES_WHIRLWIND_STRIKE_ACTIVATED("Messages.Abilities.WhirlwindStrike.Activated", "&aYou swing around and knock away all enemies!"),
    ABILITIES_WHIRLWIND_STRIKE_HIT("Messages.Abilities.WhirlwindStrike.Hit", "&cYou were blown away by the opponents axe!"),
    ABILITIES_ARES_BLESSING_ACTIVATED("Messages.Abilities.AresBlessing.Activated", "&aThe god of war blesses you with his power!"),
    ABILITIES_ARES_BLESSING_DEACTIVATED("Messages.Abilities.AresBlessing.Deactivated", "&cYour mortal body couldnt handle the power and is now weakened!"),
    ABILITIES_CIRCES_SHRINE_ACTIVATED("Messages.Abilities.CircesShrine.Activated", "&aYour offering to Circe succeeded, converting your vanilla experience into redeemable experience!"),
    ABILITIES_CIRCES_SHRINE_FAILED("Messages.Abilities.CircesShrine.Failed", "&cYour offering to Circe failed, resulting in punishment."),
    ABILITIES_CIRCES_SHRINE_ON_COOLDOWN("Messages.Abilities.CircesShrine.StillOnCooldown", "&aYour Circes Shrine is still on cooldown!"),
    GUIS_ACCEPTED_ABILITY("Messages.Guis.AcceptedAbility", "&aThe ability %Ability% has been added to your loadout!"),
    GUIS_UPGRADED_ABILITY("Messages.Guis.UpgradedAbility", "&aThe ability %Ability% has been upgraded to %Tier%!"),
    GUIS_HAS_ACTIVE("Messages.Guis.HasActive", "&cYou already have an active ability for that skill."),
    PLAYERS_LEVEL_UP("Messages.Players.LevelUp", "&eYou gained &a%Levels% &elevel(s) in %Skill%. Current Level: &e%Current_Level%"),
    PLAYERS_ABILITY_UNLOCKED("Messages.Players.AbilityUnlocked", "&eYou just unlocked %Ability%! Open up the main menu in order to accept or deny this ability."),
    PLAYERS_ABILITY_UNLOCKED_BUT_DENIED("Messages.Players.AbilityUnlockedButDenied", "&eYou just unlocked %Ability%! It was auto denied however."),
    PLAYERS_ABILITY_POINT_GAINED("Messages.Players.AbilityPointGained", "&eAbility upgrade point gained! You have &a%Ability_Points% &eto spend"),
    PLAYERS_PLAYER_READY("Messages.Players.PlayerReady", "&7You raise your %Skill_Item%"),
    PLAYERS_PLAYER_UNREADY("Messages.Players.PlayerUnready", "&7You lowered your %Skill_Item%"),
    PLAYERS_COOLDOWN_EXPIRE("Messages.Players.CooldownExpire", "&aYour cooldown for %Ability% is finished."),
    PLAYERS_COOLDOWN_ACTIVE("Messages.Players.CooldownActive", "&cYour %Skill% ability is on cooldown for &e%Time% &cseconds."),
    PLAYERS_REPLACE_COOLDOWN_EXPIRE("Messages.Players.ReplaceCooldownExpire", "&aYour cooldown for ability replacing is over."),
    TIPS_LOGIN_TIPS("Messages.Tips.LoginTips", Arrays.asList("&7[&5McRPG Tip&7]: &aCheck out /mcrpg menu to get familiar with the plugin!",
            "&7[&5McRPG Tip&7]: &aAs you level up, you can earn unlocked abilities!", "&7[&5McRPG Tip&7]: &aMake sure to check your player settings in /mcrpg!",
            "&7[&5McRPG Tip&7]: &aAbilities can be upgraded once you reach a certain level by using an ability point!",
            "&7[&5McRPG Tip&7]: &aEvery time you reach a certain power level, you gain an ability point!")),
    TIPS_LEVEL_UP_SWORDS("Messages.Tips.LevelIpSwords", Arrays.asList("&7[&5McRPG Tip&7]: &aBleed causes repeated damage for a short bit!",
            "&7[&5McRPG Tip&7]: &aRage spike allows you to crouch and dash forward, blasting enemies!",
            "&7[&5McRPG Tip&7]: &aAll bleed modifying abilities will work with Archerys Puncture!")),
    TIPS_LEVEL_UP_MINING("Messages.Tips.LevelUp.Mining",Arrays.asList("&7[&5McRPG Tip&7]: &aDouble Drop and Its A Triple do not stack!",
            "&7[&5McRPG Tip&7]: &aOre Scanner checks and points you to the nearest valuable ore!",
            "&7[&5McRPG Tip&7]: &aUse /mclink to link a chest to your Remote Transfer!", "&7[&5McRPG Tip&7]: &aUse /mcunlink to delink your chest from Remote Transfer!",
            "&7[&5McRPG Tip&7]: &aBlast Mining requires you to place TNT after readying your pick!")),
    TIPS_LEVEL_UP_UNARMED("Messages.Tips.LevelUpUnarmed", Arrays.asList("&7[&5McRPG Tip&7]: &aDense Impact makes you do 0 damage but do direct armor damage for a while!",
            "&7[&5McRPG Tip&7]: &aUse Smiting Fist to clean debuffs caused from abilities like Curse of Hades!",
            "&7[&5McRPG Tip&7]: &aDisarm will move the item into your upper inventory or if its full, it will drop the item!",
            "&7[&5McRPG Tip&7]: &aThe damage modifier from Iron Arm does not have a 100% activation rate at lower levels!")),
    TIPS_LEVEL_UP_HERBALISM("Messages.Tips.LevelUpHerbalism", Arrays.asList("&7[&5McRPG Tip&7]: &aPans Blessing requires you to bonemeal a plant after readying your hoe!",
            "&7[&5McRPG Tip&7]: &aMass Harvest will replant all crops it breaks!", "&7[&5McRPG Tip&7]: &aFarming sugar cane is the most effective way to level!",
            "&7[&5McRPG Tip&7]: &aNatures Wrath requires flowers to be in the off hand!", "&7[&5McRPG Tip&7]: &aNatures Wrath wont work if you are too hungry!")),
    TIPS_LEVEL_UP_ARCHERY("Messages.Tips.LevelUpArchery", Arrays.asList("&7[&5McRPG Tip&7]: &aThe further you shoot your target the more exp you will gain!",
            "&7[&5McRPG Tip&7]: &aCombo has a delay as to how often it activates to prevent bow spamming!",
            "&7[&5McRPG Tip&7]: &aPuncture can inflict Bleed and use all modifiers from your Swords skill!", "&7[&5McRPG Tip&7]: &aBlessing of Artemis is good for a sneaky surprise!",
            "&7[&5McRPG Tip&7]: &aReady your bow by attacking air before you shoot to activate abilities!")),
    TIPS_LEVEL_UP_WOODCUTTING("Messages.Tips.LevelUpWoodcutting", Arrays.asList("&7[&5McRPG Tip&7]: &aHeavy Swing will mine surrounding wood and leaves of the same type!",
            "&7[&5McRPG Tip&7]: &aHeavy Swing only works on natural blocks so no need to worry about it ruining your builds!",
            "&7[&5McRPG Tip&7]: &aToss a sapling into a block of water surrounded by gold blocks to activate Demeters Shrine!", "&7[&5McRPG Tip&7]: &aMoving in a forest will activate Nymphs Vitality!",
            "&7[&5McRPG Tip&7]: &aReady your axe and mine a sapling in order to harvest the trees future self using Temporal Harvest!")),
    TIPS_LEVEL_UP_FITNESS("Messages.Tips.LevelUpFitness", Arrays.asList("&7[&5McRPG Tip&7]: &aDue to how universal Fitness is, you can only have two Fitness abilities at once!",
            "&7[&5McRPG Tip&7]: &aBullet Proof negates all projectiles when activated, including Archery abilities!", "&7[&5McRPG Tip&7]: &aGain Fitness exp by falling or taking damage from an mob or player",
                    "&7[&5McRPG Tip&7]: &aWearing Feather Falling increases exp gained from falling.")),
    TIPS_LEVEL_UP_EXCAVATION("Messages.Tips.LevelUpExcavation", Arrays.asList("&7[&5McRPG Tip&7]: &aPans Shrine requires a block of water surrounded on 4 sides by emerald blocks!",
            "&7[&5McRPG Tip&7]: &aFrenzy Dig will give haste and increase chance of doubling block drops for a short while!", "&7[&5McRPG Tip&7]: &aMana Deposit will give you exp in a random skill occasionally!",
            "&7[&5McRPG Tip&7]: &aActivate Pans Shrine to change the landscape!")),
    TIPS_LEVEL_UP_AXES("Messages.Tips.LevelUpAxes", Arrays.asList("&7[&5McRPG Tip&7]: &aShred will quickly whittle down opponents armour durability!",
            "&7[&5McRPG Tip&7]: &aAres Blessing will buff you for a short while, but then leave you in a long weakened state!", "&7[&5McRPG Tip&7]: &aDifferent types of axes will give more or less exp per hit!",
            "&7[&5McRPG Tip&7]: &aUse Whirlwind Strike when surrounded to knockback enemies!")),
    TIPS_LEVEL_UP_FISHING("Messages.Tips.LevelUpFishing", Arrays.asList("&7[&5McRPG Tip&7]: &aGreat Rod increases your chance of finding treasure!",
            "&7[&5McRPG Tip&7]: &aUsing Luck Of The Sea makes it more likely to get treasure and makes junk more rare!", "&7[&5McRPG Tip&7]: &aShake has a small chance of making mobs drop related item!",
            "&7[&5McRPG Tip&7]: &aSunken Armory can even fish up diamond armor!", "&7[&5McRPG Tip&7]: &aSuper Rod makes treasure found even more amazing!", "&7[&5McRPG Tip&7]: &aMagic Touch will let you fish enchanted books and gear!")),
    TIPS_LEVEL_UP_SORCERY("Messages.Tips.LevelUpSorcery", Arrays.asList("&7[&5McRPG Tip&7]: &aHasty Brew increases the speed at which your potions brew!",
            "&7[&5McRPG Tip&7]: &aHades Domain increases all exp gain while in the nether!", "&7[&5McRPG Tip&7]: &aCirces Recipes will allow you to brew a wide range of unique potions!",
            "&7[&5McRPG Tip&7]: &aYou can get rare items such as skill books or artifacts from brewing!", "&7[&5McRPG Tip&7]: &aEnchanting will give Sorcery exp!", "&7[&5McRPG Tip&7]: &aArtifacts are consumables that can be found from brewing!")),
    TIPS_LEVEL_UP_TAMING("Messages.Tips.LevelUpTaming", Arrays.asList("&7[&5McRPG Tip&7]: &aGore will inflict Bleed on an enemy along with any modifiers!", "&7[&5McRPG Tip&7]: &aComradery will let nearby wolves take damage for you!", "&7[&5McRPG Tip&7]: &aUse Call Of The Wild to summon an animal to your side!",
      "&7[&5McRPG Tip&7]: &aUsing Prismarine Shards, you can use Call Of The Wild to summon tropical fish!", "&7[&5McRPG Tip&7]: &aMobs summoned by Call Of The Wild cant be bred!", "&7[&5McRPG Tip&7]: &aCrystalized Blood has many applications! Bleeding enemies have a higher drop rate!")),
    TIPS_LEVEL_UP_PARTY("Messages.Tips.LevelUpParty", Arrays.asList("&7[&5McRPG Tip&7]: &aEvery time your party levels up, you gain an upgrade point!", "&7[&5McRPG Tip&7]: &aParty owners can change role permissions by doing /mcparty roles!",
      "&7[&5McRPG Tip&7]: &aPlayers with a specific role can access the private bank by doing /mcparty storage!", "&7[&5McRPG Tip&7]: &aYou can spend upgrade points to increase the private party size!", "&7[&5McRPG Tip&7]: &aYou can spend upgrade points to increase the amount of exp shared"));

    private String path;
    private Object defaultValue;
    private String[] comments;


    LangEnum(String path, Object defaultValue, String... comments) {
        this.path = path;
        this.defaultValue = defaultValue;
        this.comments = comments;
    }


    @Override
    public String getPath() {
        return path;
    }

    @Override
    public Object getDefaultValue() {
        return defaultValue;
    }

    @Override
    public String[] getComments() {
        return comments;
    }
}
