Size: 45
Title: '&4Change your settings'
ChangeDisplaySettings:
  ScoreBoard: '&c&nDisplay Type:&r &6Score Board'
  BossBar: '&c&nDisplay Type:&r &6Boss Bar'
  ActionBar: '&c&nDisplay Type:&r &6Action Bar'
  Slot: 10
  Lore:
    - ' '
    - '&6Click &3this to change your display type'
    - '&3When using &6/mcdisplay {skill}'
KeepHandEmpty:
  Enabled: '&c&nKeep Hand Empty:&r &2Enabled'
  Disabled: '&c&nKeep Hand Empty:&r &4Disabled'
  Slot: 12
  Lore:
    - ' '
    - '&6Click &3this to change'
    - '&3if items should go into your empty hand'
MobHealthDisplay:
  Bar: '&c&nMob Health Display:&r &6Bar'
  Hearts: '&c&nMob Health Display:&r &6Hearts'
  None: '&c&nMob Health Display:&r &4Disabled'
  Slot: 14
  Lore:
    - ' '
    - '&6Click &3this to change your display type'
    - '&3above mobs when fighting them'
AutoDenyNewAbilities:
  Enabled: '&c&nAuto Deny New Abilities:&r &2Enabled'
  Disabled: '&c&nAuto Deny New Abilities:&r &4Disabled'
  Slot: 16
  Lore:
    - ' '
    - '&6Click &3this to change'
    - '&3if new abilities should auto deny'
IgnoreTips:
  Enabled: '&c&nIgnoring Tips:&r &2Enabled'
  Disabled: '&c&nIgnoring Tips:&r &4Disabled'
  Slot: 28
  Lore:
    - ' '
    - '&6Click &3this to change'
    - '&3if tips should be ignored'
EmptyOffHand:
  Enabled: '&aOff Hand Must Be Empty'
  Disabled: '&cOff Hand Can Have An Item In It'
  Slot: 30
  Lore:
    - ' '
    - '&3If enabled, then in order to ready'
    - '&3abilities, your offhand must be empty.'
UnarmedIgnoreSlot:
  Enabled: '&aSlot &6#%Slot% &cIs Being Kept Empty'
  Disabled: '&cCurrently &6No Slot &cIs Being Kept Empty'
  Slot: 32
  Lore:
    - ' '
    - '&3If enabled, this setting will keep picked up'
    - '&3items from going into the selected slot'
AutoAcceptPartyTP:
  Enabled: '&c&nAuto Accept TPs:&r &2Enabled'
  Disabled: '&c&nAuto Accept TPs:&r &4Disabled'
  Slot: 34
  Lore:
    - '&3If enabled, then any party teleport'
    - '&3requests will be auto accepted'
AddLater:
  DisplayName: '&cThis feature will be added later'
  Lore: {}
  Slot: 34
BackButton:
  Material: BARRIER
  DisplayName: '&c<<Back'
  Slot: 36
  Lore:
    - '&6Click &3this to go back'
FillerItem:
  Material: GRAY_STAINED_GLASS_PANE
  Amount: 1
  DisplayName: ' '
  Lore: {}