package us.eunoians.mcrpg.listener.quest;

import com.diamonddagger590.mccore.database.Database;
import com.diamonddagger590.mccore.registry.RegistryAccess;
import com.diamonddagger590.mccore.registry.RegistryKey;
import org.bukkit.NamespacedKey;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.jetbrains.annotations.NotNull;
import us.eunoians.mcrpg.McRPG;
import us.eunoians.mcrpg.database.table.board.PlayerBoardStateDAO;
import us.eunoians.mcrpg.entity.player.McRPGPlayer;
import us.eunoians.mcrpg.event.quest.QuestCancelEvent;
import us.eunoians.mcrpg.quest.QuestManager;
import us.eunoians.mcrpg.quest.definition.QuestDefinitionRegistry;
import us.eunoians.mcrpg.quest.impl.QuestInstance;
import us.eunoians.mcrpg.quest.source.builtin.BoardPersonalQuestSource;
import us.eunoians.mcrpg.registry.McRPGRegistryKey;
import us.eunoians.mcrpg.registry.manager.McRPGManagerKey;

import java.sql.Connection;
import java.util.UUID;
import java.util.logging.Level;

/**
 * Listens for {@link QuestCancelEvent} and retires the quest from Tier 1 (active)
 * to Tier 2 (cache). This handles both manual cancellations and cancellations
 * triggered by quest expiration.
 * <p>
 * Runs at {@link EventPriority#MONITOR} so external listeners can react first.
 */
public class QuestCancelListener implements Listener {

    /**
     * Handles quest cancellation: moves the quest from the active map to the
     * finished cache and removes it from the player contribution index.
     */
    @EventHandler(priority = EventPriority.MONITOR)
    public void onQuestCancel(@NotNull QuestCancelEvent event) {
        QuestManager questManager = RegistryAccess.registryAccess().registry(RegistryKey.MANAGER)
                .manager(McRPGManagerKey.QUEST);
        questManager.retireQuest(event.getQuestInstance());

        releaseBoardSlot(event.getQuestInstance());
        decrementBoardCount(event.getQuestInstance());
        deregisterEphemeralDefinition(event.getQuestInstance().getQuestKey());
    }

    /**
     * Deregisters an ephemeral quest definition (generated by the template engine)
     * after the quest reaches a terminal state. Generated keys follow the
     * {@code gen_} prefix convention.
     *
     * @param questKey the quest definition key to check and potentially deregister
     */
    private void releaseBoardSlot(@NotNull QuestInstance questInstance) {
        var dbManager = RegistryAccess.registryAccess().registry(RegistryKey.MANAGER)
                .manager(McRPGManagerKey.DATABASE);
        if (dbManager == null) {
            return;
        }
        Database database = dbManager.getDatabase();
        UUID questUUID = questInstance.getQuestUUID();
        database.getDatabaseExecutorService().submit(() -> {
            try (Connection connection = database.getConnection()) {
                PlayerBoardStateDAO.updateStateByQuestInstanceUUID(connection, questUUID, "CANCELLED");
            } catch (Exception e) {
                McRPG.getInstance().getLogger().log(Level.WARNING,
                        "Failed to release board slot for cancelled quest " + questUUID, e);
            }
        });
    }

    private void decrementBoardCount(@NotNull QuestInstance questInstance) {
        if (!questInstance.getQuestSource().getKey().equals(BoardPersonalQuestSource.KEY)) {
            return;
        }
        questInstance.getQuestScope().ifPresent(scope -> {
            for (UUID playerUUID : scope.getCurrentPlayersInScope()) {
                RegistryAccess.registryAccess().registry(RegistryKey.MANAGER)
                        .manager(McRPGManagerKey.PLAYER)
                        .<McRPGPlayer>getPlayer(playerUUID)
                        .ifPresent(p -> p.asQuestHolder().decrementBoardQuestCount());
            }
        });
    }

    private void deregisterEphemeralDefinition(@NotNull NamespacedKey questKey) {
        if (questKey.getKey().startsWith("gen_")) {
            QuestDefinitionRegistry definitionRegistry = RegistryAccess.registryAccess()
                    .registry(McRPGRegistryKey.QUEST_DEFINITION);
            if (definitionRegistry.deregister(questKey)) {
                McRPG.getInstance().getLogger().fine(
                        "Deregistered ephemeral definition " + questKey);
            }
        }
    }
}
