config-version: 1
skill-enabled: true
permissions:
  restrict-skill-to-permission: false
  use-permissions-to-unlock-abilities: false
  use-permissions-to-activate-abilities: false
leveling:
  level-up-equation: '2000+(20*(skill_level))'
  maximum-skill-level: 1000
experience:
  sources:
    STONE: 2
ability-configuration:
  extra-ore:
    enabled: true
    activation-equation: (mining_level)*.033
    valid-drops:
      - COPPER_ORE
      - DEEPSLATE_COPPER_ORE
      - COAL_ORE
      - DEEPSLATE_COAL_ORE
      - IRON_ORE
      - DEEPSLATE_IRON_ORE
      - GOLD_ORE
      - DEEPSLATE_GOLD_ORE
      - DIAMOND_ORE
      - DEEPSLATE_IRON_ORE
      - EMERALD_ORE
      - DEEPSLATE_EMERALD_ORE
      - LAPIS_ORE
      - DEEPSLATE_LAPIS_ORE
      - REDSTONE_ORE
      - DEEPSLATE_REDSTONE_ORE
      - NETHER_GOLD_ORE
      - NETHER_QUARTZ_ORE
  its-a-triple:
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        activation-chance: 3.0
      tier-2:
        unlock-level: 2
        activation-chance: 4.0
      tier-3:
        unlock-level: 3
        activation-chance: 5.0
      tier-4:
        unlock-level: 4
        activation-chance: 7.5
      tier-5:
        unlock-level: 5
        activation-chance: 10.0
  remote-transfer:
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    allowed-blocks:
      nether:
        - ANCIENT_DEBRIS
        - BASALT
        - BLACKSTONE
        - BONE_BLOCK
        - CRYING_OBSIDIAN
        - GILDED_BLACKSTONE
        - GLOWSTONE
        - GLOWSTONE_DUST
        - MAGMA_BLOCK
        - NETHER_BRICK
        - QUARTZ
      ores:
        - COAL
        - COAL_ORE
        - COPPER_INGOT
        - COPPER_ORE
        - DEEPSLATE_COAL_ORE
        - DEEPSLATE_COPPER_ORE
        - DEEPSLATE_DIAMOND_ORE
        - DEEPSLATE_EMERALD_ORE
        - DEEPSLATE_GOLD_ORE
        - DEEPSLATE_IRON_ORE
        - DEEPSLATE_LAPIS_ORE
        - DEEPSLATE_REDSTONE_ORE
        - DIAMOND
        - DIAMOND_ORE
        - EMERALD
        - EMERALD_ORE
        - GOLD_INGOT
        - GOLD_NUGGET
        - GOLD_ORE
        - IRON_INGOT
        - IRON_NUGGET
        - IRON_ORE
        - LAPIS_LAZULI
        - LAPIS_ORE
        - NETHER_GOLD_ORE
        - NETHER_QUARTZ_ORE
        - RAW_COPPER
        - RAW_GOLD
        - RAW_IRON
        - REDSTONE
        - REDSTONE_ORE
      caves:
        - AMETHYST_BLOCK
        - AMETHYST_CLUSTER
        - ANDESITE
        - CALCITE
        - COBBLED_DEEPSLATE
        - COBBLESTONE
        - DEEPSLATE
        - DIORITE
        - DRIPSTONE_BLOCK
        - GRANITE
        - OBSIDIAN
        - POINTED_DRIPSTONE
        - TUFF
      end:
        - END_STONE
      ocean:
        - DARK_PRISMARINE
        - PRISMARINE
        - PRISMARINE_CRYSTALS
        - PRISMARINE_SHARD
      terracotta:
        - BLACK_TERRACOTTA
        - BLUE_TERRACOTTA
        - BROWN_TERRACOTTA
        - CYAN_TERRACOTTA
        - GRAY_TERRACOTTA
        - GREEN_TERRACOTTA
        - LIGHT_BLUE_TERRACOTTA
        - LIGHT_GRAY_TERRACOTTA
        - LIME_TERRACOTTA
        - MAGENTA_TERRACOTTA
        - ORANGE_TERRACOTTA
        - PINK_TERRACOTTA
        - PURPLE_TERRACOTTA
        - RED_TERRACOTTA
        - TERRACOTTA
        - WHITE_TERRACOTTA
        - YELLOW_TERRACOTTA
      overworld:
        - MOSSY_COBBLESTONE
        - MOSSY_STONE_BRICKS
        - RED_SANDSTONE
        - SANDSTONE
        - STONE
      # custom:
      # - STONE:1
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        maximum-distance: 50