config-version: 1
# Is this skill enabled or not. If disabled, players won't be able to gain experience
# and this will turn off any abilities belonging to the skill.
skill-enabled: true
permissions:
  restrict-skill-to-permission: false
  use-permissions-to-unlock-abilities: false
  use-permissions-to-activate-abilities: false
# Configure leveling requirements for this skill.
leveling:
  # Configure the equation to calculate the player's experience for the next level
  level-up-equation: '200+(0.17*(skill_level^1.669))'
  # Configure the maximum level this skill can be
  maximum-skill-level: 1000
# Configure experience gain for this skill
experience:
  # Configure what items a player can use to break blocks with in order to gain experience.
  # These items can be either material values such as WOODEN_PICKAXE
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  allowed-items-for-experience-gain:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - COPPER_PICKAXE
    - GOLDEN_PICKAXE
    - IRON_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE
  # Configure how much experience gain should be multiplied by based
  # on what item the player is holding in their main hand. If an item
  # isn't in this list but is allowed, then the default value of 1.0 is used.
  #
  # These modifiers can be either material values such as WOODEN_PICKAXE
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  material-modifiers:
    GOLDEN_PICKAXE: 2.0
  # Configure what blocks a player can break to gain experience and how
  # much experience breaking that block will give.
  #
  # These sources can be either material values such as ANDESITE
  # or the custom block id for whatever custom block plugin you might be using
  # if you want to allow custom blocks.
  sources:
    ANCIENT_DEBRIS: 3000
    ANDESITE: 2
    COBBLESTONE: 2
    AMETHYST_BLOCK: 100
    AMETHYST_CLUSTER: 200
    BUDDING_AMETHYST: 150
    BASALT: 5
    BLACK_TERRACOTTA: 20
    BLACKSTONE: 5
    BLUE_ICE: 20
    BLUE_TERRACOTTA: 20
    BONE_BLOCK: 100
    BRICKS: 10
    BROWN_TERRACOTTA: 20
    CALCITE: 10
    COAL_ORE: 50
    COPPER_ORE: 50
    COBBLED_DEEPSLATE: 2
    CRACKED_DEEPSLATE_BRICKS: 10
    CRACKED_DEEPSLATE_TILES: 10
    CRACKED_NETHER_BRICKS: 10
    CRACKED_POLISHED_BLACKSTONE_BRICKS: 10
    CRACKED_STONE_BRICKS: 10
    CRYING_OBSIDIAN: 200
    CYAN_TERRACOTTA: 20
    DEEPSLATE_BRICKS: 10
    DEEPSLATE_COAL_ORE: 100
    DEEPSLATE_COPPER_ORE: 100
    DEEPSLATE_DIAMOND_ORE: 1500
    DEEPSLATE_EMERALD_ORE: 3000
    DEEPSLATE_GOLD_ORE: 500
    DEEPSLATE_IRON_ORE: 200
    DEEPSLATE_LAPIS_ORE: 400
    DEEPSLATE_REDSTONE_ORE: 300
    DIAMOND_ORE: 750
    DIORITE: 2
    DRIPSTONE_BLOCK: 5
    EMERALD_ORE: 1500
    END_CRYSTAL: 3000
    END_STONE: 20
    GILDED_BLACKSTONE: 10
    GLOWSTONE: 20
    GOLD_ORE: 250
    GRANITE: 2
    GRAY_TERRACOTTA: 20
    GREEN_TERRACOTTA: 20
    ICE: 10
    INFESTED_COBBLESTONE: 2
    INFESTED_DEEPSLATE: 2
    INFESTED_STONE: 2
    IRON_ORE: 100
    LAPIS_ORE: 200
    LIGHT_BLUE_TERRACOTTA: 20
    LIGHT_GRAY_TERRACOTTA: 20
    LIME_TERRACOTTA: 20
    MAGENTA_TERRACOTTA: 20
    MAGMA_BLOCK: 20
    MOSSY_COBBLESTONE: 5
    MOSSY_STONE_BRICKS: 5
    NETHER_BRICK: 5
    NETHER_GOLD_ORE: 125
    NETHER_QUARTZ_ORE: 100
    NETHERRACK: 2
    OBSIDIAN: 200
    ORANGE_TERRACOTTA: 20
    PACKED_ICE: 20
    PINK_TERRACOTTA: 20
    POINTED_DRIPSTONE: 5
    PRISMARINE: 20
    PRISMARINE_BRICKS: 20
    PURPLE_TERRACOTTA: 20
    PURPUR_BLOCK: 20
    PURPUR_PILLAR: 20
    RED_NETHER_BRICKS: 10
    RED_SANDSTONE: 5
    RED_TERRACOTTA: 20
    SANDSTONE: 5
    SCULK: 5
    SEA_LANTERN: 50
    SPAWNER: 2000
    STONE: 2
    STONE_BRICKS: 2
    TERRACOTTA: 5
    TUFF: 2
    WHITE_TERRACOTTA: 20
    YELLOW_TERRACOTTA: 20
ability-configuration:
  extra-ore:
    enabled: true
    activation-equation: (mining_level)*.033
    valid-drops:
      - COPPER_ORE
      - DEEPSLATE_COPPER_ORE
      - COAL_ORE
      - DEEPSLATE_COAL_ORE
      - IRON_ORE
      - DEEPSLATE_IRON_ORE
      - GOLD_ORE
      - DEEPSLATE_GOLD_ORE
      - DIAMOND_ORE
      - DEEPSLATE_IRON_ORE
      - EMERALD_ORE
      - DEEPSLATE_EMERALD_ORE
      - LAPIS_ORE
      - DEEPSLATE_LAPIS_ORE
      - REDSTONE_ORE
      - DEEPSLATE_REDSTONE_ORE
      - NETHER_GOLD_ORE
      - NETHER_QUARTZ_ORE
  its-a-triple:
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        activation-chance: 3.0
      tier-2:
        unlock-level: 2
        activation-chance: 4.0
      tier-3:
        unlock-level: 3
        activation-chance: 5.0
      tier-4:
        unlock-level: 4
        activation-chance: 7.5
      tier-5:
        unlock-level: 5
        activation-chance: 10.0
  remote-transfer:
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    # What different categories of blocks can players toggle?
    # These categories are used for filtering specific blocks to make
    # it easier to search for specific ones.
    #
    # These categories should match exactly to the ones in the en.yml under gui.remote-transfer-gui.categories.
    # The "all" category is an internal concept and should not be defined here.
    # If any category is defined here but not in the en.yml, you will get errors.
    categories:
      # The identifier of the category. You will use this in the en.yml to configure UI elements
      nether:
        # A list of materials or custom item identifiers if you want to support custom blocks from something like Nexo
        - ANCIENT_DEBRIS
        - BASALT
        - BLACKSTONE
        - BONE_BLOCK
        - CRYING_OBSIDIAN
        - GILDED_BLACKSTONE
        - GLOWSTONE
        - GLOWSTONE_DUST
        - MAGMA_BLOCK
        - NETHER_BRICK
        - QUARTZ
      ores:
        - COAL
        - COAL_ORE
        - COPPER_INGOT
        - COPPER_ORE
        - DEEPSLATE_COAL_ORE
        - DEEPSLATE_COPPER_ORE
        - DEEPSLATE_DIAMOND_ORE
        - DEEPSLATE_EMERALD_ORE
        - DEEPSLATE_GOLD_ORE
        - DEEPSLATE_IRON_ORE
        - DEEPSLATE_LAPIS_ORE
        - DEEPSLATE_REDSTONE_ORE
        - DIAMOND
        - DIAMOND_ORE
        - EMERALD
        - EMERALD_ORE
        - GOLD_INGOT
        - GOLD_NUGGET
        - GOLD_ORE
        - IRON_INGOT
        - IRON_NUGGET
        - IRON_ORE
        - LAPIS_LAZULI
        - LAPIS_ORE
        - NETHER_GOLD_ORE
        - NETHER_QUARTZ_ORE
        - RAW_COPPER
        - RAW_GOLD
        - RAW_IRON
        - REDSTONE
        - REDSTONE_ORE
      caves:
        - AMETHYST_BLOCK
        - AMETHYST_CLUSTER
        - ANDESITE
        - CALCITE
        - COBBLED_DEEPSLATE
        - COBBLESTONE
        - DEEPSLATE
        - DIORITE
        - DRIPSTONE_BLOCK
        - GRANITE
        - OBSIDIAN
        - POINTED_DRIPSTONE
        - TUFF
      end:
        - END_STONE
      ocean:
        - DARK_PRISMARINE
        - PRISMARINE
        - PRISMARINE_CRYSTALS
        - PRISMARINE_SHARD
      terracotta:
        - BLACK_TERRACOTTA
        - BLUE_TERRACOTTA
        - BROWN_TERRACOTTA
        - CYAN_TERRACOTTA
        - GRAY_TERRACOTTA
        - GREEN_TERRACOTTA
        - LIGHT_BLUE_TERRACOTTA
        - LIGHT_GRAY_TERRACOTTA
        - LIME_TERRACOTTA
        - MAGENTA_TERRACOTTA
        - ORANGE_TERRACOTTA
        - PINK_TERRACOTTA
        - PURPLE_TERRACOTTA
        - RED_TERRACOTTA
        - TERRACOTTA
        - WHITE_TERRACOTTA
        - YELLOW_TERRACOTTA
      overworld:
        - MOSSY_COBBLESTONE
        - MOSSY_STONE_BRICKS
        - RED_SANDSTONE
        - SANDSTONE
        - STONE
      # custom:
      # - STONE:1
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        unlock-level: 1*tier
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        maximum-distance: 50
  ore-scanner:
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    block-types:
      copper:
        type-name: "Copper Ore"
        color-code: 'c'
        weight: 1
        materials:
          - "COPPER_ORE"
          - "DEEPSLATE_COPPER_ORE"
      iron:
        type-name: "Iron Ore"
        color-code: 'e'
        weight: 1
        materials:
          - "IRON_ORE"
          - "DEEPSLATE_IRON_ORE"
      redstone:
        type-name: "Redstone Ore"
        color-code: '4'
        weight: 3
        materials:
          - "REDSTONE_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
      lapis:
        type-name: "Lapis Ore"
        color-code: '9'
        weight: 4
        materials:
          - "LAPIS_ORE"
          - "DEEPSLATE_LAPIS_ORE"
      gold:
        type-name: "Gold Ore"
        color-code: '6'
        weight: 5
        materials:
          - "GOLD_ORE"
          - "DEEPSLATE_GOLD_ORE"
      emerald:
        type-name: "Emerald Ore"
        color-code: 'a'
        weight: 6
        materials:
          - "EMERALD_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      diamond:
        type-name: "Diamond Ore"
        color-code: 'b'
        weight: 7
        materials:
          - "DIAMOND_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
        cooldown: 180
      tier-1:
        unlock-level: 1
        range: 10
      tier-2:
        unlock-level: 2
        range: 10
      tier-3:
        unlock-level: 3
        range: 10
      tier-4:
        unlock-level: 4
        range: 10
      tier-5:
        unlock-level: 5
        range: 10
