config-version: 1
# Is this skill enabled or not. If disabled, players won't be able to gain experience
# and this will turn off any abilities belonging to the skill.
skill-enabled: true
permissions:
  restrict-skill-to-permission: false
  use-permissions-to-unlock-abilities: false
  use-permissions-to-activate-abilities: false
# Configure leveling requirements for this skill.
leveling:
  # Configure the equation to calculate the player's experience for the next level
  level-up-equation: '200+(0.17*(skill_level^1.669))'
  # Configure the maximum level this skill can be
  maximum-skill-level: 1000
# Configure experience gain for this skill
experience:
  # Configure what items a player can use to attack mobs with in order to gain experience.
  # These items can be either material values such as WOODEN_SWORD
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  allowed-items-for-experience-gain:
    - WOODEN_SWORD
    - STONE_SWORD
    - COPPER_SWORD
    - GOLDEN_SWORD
    - IRON_SWORD
    - DIAMOND_SWORD
    - NETHERITE_SWORD
  # Configure how much experience gain should be multiplied by based
  # on what item the player is holding in their main hand. If an item
  # isn't in this list but is allowed, then the default value of 1.0 is used.
  #
  # These modifiers can be either material values such as WOODEN_SWORD
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  material-modifiers:
    GOLDEN_SWORD: 2.0
  # Configure what mobs a player can attack to gain experience and how
  # much experience attacking that mob will give per 1 damage dealt.
  #
  # These sources can be either entity type values such as CHICKEN
  # or the custom entity id for whatever custom entity plugin you might be using
  # if you want to allow custom entity.
  sources:
    ALLAY: 10
    AXOLOTL: 10
    BAT: 10
    BEE: 10
    BLAZE: 30
    BOGGED: 20
    BREEZE: 30
    CAMEL: 10
    CAT: 5
    CAVE_SPIDER: 15
    CHICKEN: 5
    COD: 5
    COW: 5
    CREAKING: 50
    CREEPER: 20
    DOLPHIN: 10
    DONKEY: 5
    DROWNED: 20
    ELDER_GUARDIAN: 100
    ENDER_DRAGON: 100
    ENDERMAN: 30
    ENDERMITE: 20
    EVOKER: 50
    FOX: 10
    FROG: 10
    GHAST: 50
    GIANT: 50
    GLOW_SQUID: 10
    GUARDIAN: 30
    HAPPY_GHAST: 10
    HOGLIN: 15
    HORSE: 5
    HUSK: 20
    ILLUSIONER: 50
    IRON_GOLEM: 20
    LLAMA: 10
    MAGMA_CUBE: 20
    MOOSHROOM: 5
    MULE: 10
    OCELOT: 10
    PANDA: 10
    PARROT: 5
    PHANTOM: 15
    PIG: 5
    PIGLIN: 15
    PIGLIN_BRUTE: 30
    PILLAGER: 20
    PLAYER: 10
    POLAR_BEAR: 10
    PUFFERFISH: 10
    RABBIT: 10
    RAVAGER: 20
    SALMON: 5
    SHEEP: 5
    SHULKER: 30
    SILVERFISH: 5
    SKELETON: 15
    SKELETON_HORSE: 10
    SLIME: 15
    SNIFFER: 10
    SNOW_GOLEM: 5
    SPIDER: 15
    SQUID: 10
    STRAY: 20
    STRIDER: 10
    TADPOLE: 10
    TRADER_LLAMA: 20
    TROPICAL_FISH: 5
    TURTLE: 10
    VEX: 15
    VILLAGER: 5
    VINDICATOR: 20
    WANDERING_TRADER: 10
    WARDEN: 50
    WITCH: 20
    WITHER: 100
    WITHER_SKELETON: 50
    WOLF: 5
    ZOGLIN: 15
    ZOMBIE: 15
    ZOMBIE_HORSE: 10
    ZOMBIE_VILLAGER: 20
    ZOMBIFIED_PIGLIN: 15
ability-configuration:
  bleed:
    enabled: true
    activation-equation: (swords_level)*.033
    minimum-health-allowed: 4
    bleed-base-cycles: 6
    bleed-base-frequency: 0.5
    bleed-base-damage: 1
    grant-bleed-immunity-after-expire: true
    bleed-immunity-duration: 5
    bleed-damage-pierce-armor: true
  enhanced-bleed:
    # If this ability should be enabled
    enabled: true
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      # - enhanced-bleed-base-damage-increase: integer
      # - enhanced-bleed-activation-chance: decimal from 0.0-100.0
      # - enhanced-bleed-damage-boost: integer
      all-tiers:
        #How much should the damage of Bleed increase by before adding possible additional damage
        enhanced-bleed-base-damage-increase: 1
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 50
        # The chance of Enhanced Bleed activating bonus damage whenever Bleed is inflicted (on top of the base damage increase)
        enhanced-bleed-activation-chance: 20.0
        # How much should the damage of Bleed increase if Enhanced Bleed activates (on top of the base damage increase)
        enhanced-bleed-damage-boost: 1
      tier-2:
        unlock-level: 125
        enhanced-bleed-activation-chance: 30.0
        enhanced-bleed-damage-boost: 1
      tier-3:
        unlock-level: 250
        enhanced-bleed-activation-chance: 35.0
        enhanced-bleed-damage-boost: 2
      tier-4:
        upgrade-point-cost: 2
        unlock-level: 375
        enhanced-bleed-activation-chance: 55.0
        enhanced-bleed-damage-boost: 2
      tier-5:
        upgrade-point-cost: 2
        unlock-level: 500
        enhanced-bleed-base-damage-increase: 2
        enhanced-bleed-activation-chance: 70.0
        enhanced-bleed-damage-boost: 2
  deeper-wound:
    enabled: true
    amount-of-tiers: 5
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      # - deeper-wound-activation-chance: decimal from 0.0-100.0
      # - deeper-wound-cycle-increase: integer
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SKELETON
      tier-1:
        unlock-level: 150
        # The chance of Deeper Wound activating bonus duration whenever Bleed is inflicted
        deeper-wound-activation-chance: 20.0
        # How many more cycles should Bleed have if Deeper Wound activates
        deeper-wound-cycle-increase: 2
      tier-2:
        unlock-level: 275
        deeper-wound-activation-chance: 30.0
        deeper-wound-cycle-increase: 2
      tier-3:
        unlock-level: 425
        deeper-wound-activation-chance: 40.0
        deeper-wound-cycle-increase: 3
      tier-4:
        upgrade-point-cost: 2
        unlock-level: 575
        deeper-wound-activation-chance: 50.0
        deeper-wound-cycle-increase: 6
      tier-5:
        upgrade-point-cost: 2
        unlock-level: 700
        deeper-wound-activation-chance: 60.0
        deeper-wound-cycle-increase: 8
  vampire:
    enabled: true
    amount-of-tiers: 5
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      # - vampire-activation-chance: decimal from 0.0-100.0
      # - amount-to-heal: integer
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - ZOMBIE
              - DROWNED
      tier-1:
        unlock-level: 250
        # The chance of Vampire activating whenever bleed is inflicted
        vampire-activation-chance: 20.0
        # The amount of health to heal per bleed cycle
        amount-to-heal: 1
      tier-2:
        unlock-level: 400
        vampire-activation-chance: 30.0
        amount-to-heal: 1
      tier-3:
        unlock-level: 550
        vampire-activation-chance: 50.0
        amount-to-heal: 1
      tier-4:
        upgrade-point-cost: 2
        unlock-level: 700
        vampire-activation-chance: 80.0
        amount-to-heal: 1
      tier-5:
        upgrade-point-cost: 2
        unlock-level: 850
        vampire-activation-chance: 100.0
        amount-to-heal: 1
  serrated-strikes:
    enabled: true
    amount-of-tiers: 5
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - ZOMBIE
              - DROWNED
      tier-1:
        unlock-level: 1
        cooldown: 240
        duration: 2
        bleed-activation-boost: 5.0
      tier-2:
        unlock-level: 2
        cooldown: 220
        duration: 3
        bleed-activation-boost: 7.5
      tier-3:
        unlock-level: 3
        cooldown: 200
        duration: 5
        bleed-activation-boost: 10.0
      tier-4:
        upgrade-point-cost: 2
        unlock-level: 700
        cooldown: 160
        duration: 7
      tier-5:
        upgrade-point-cost: 2
        unlock-level: 850
        cooldown: 120
        duration: 10
  rage-spike:
    enabled: true
    amount-of-tiers: 5
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - ZOMBIE
              - DROWNED
      tier-1:
        unlock-level: 1
        cooldown: 240
      tier-2:
        unlock-level: 2
        cooldown: 220
      tier-3:
        unlock-level: 3
        cooldown: 200
      tier-4:
        upgrade-point-cost: 2
        unlock-level: 700
        cooldown: 160
      tier-5:
        upgrade-point-cost: 2
        unlock-level: 850
        cooldown: 120