config-version: 1
skill-enabled: true
permissions:
  restrict-skill-to-permission: false
  use-permissions-to-unlock-abilities: false
  use-permissions-to-activate-abilities: false
leveling:
  level-up-equation: '200+(0.17*(skill_level^1.669))'
  maximum-skill-level: 1000
experience:
  # Configure what items a player can use to break blocks with in order to gain experience.
  # These items can be either material values such as WOODEN_AXE
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  allowed-items-for-experience-gain:
    - WOODEN_AXE
    - STONE_AXE
    - GOLDEN_AXE
    - IRON_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE
    - AIR
  # Configure how much experience gain should be multiplied by based
  # on what item the player is holding in their main hand. If an item
  # isn't in this list but is allowed, then the default value of 1.0 is used.
  #
  # These modifiers can be either material values such as WOODEN_AXE
  # or the custom item id for whatever custom item plugin you might be using
  # if you want to allow custom items.
  material-modifiers:
    GOLDEN_AXE: 2.0
  # Configure what blocks a player can break to gain experience and how
  # much experience breaking that block will give.
  #
  # These sources can be either material values such as ANDESITE
  # or the custom block id for whatever custom block plugin you might be using
  # if you want to allow custom blocks.
  sources:
    ACACIA_LOG: 40
    BAMBOO: 2
    BIRCH_LOG: 25
    CHERRY_LOG: 40
    CREAKING_HEART: 2000
    CRIMSON_HYPHAE: 40
    CRIMSON_STEM: 40
    DARK_OAK_LOG: 25
    JUNGLE_LOG: 25
    MANGROVE_LOG: 40
    OAK_LOG: 25
    PALE_OAK_LOG: 40
    SPRUCE_LOG: 25
    STRIPPED_ACACIA_LOG: 40
    STRIPPED_BIRCH_LOG: 25
    STRIPPED_CHERRY_LOG: 40
    STRIPPED_CRIMSON_HYPHAE: 40
    STRIPPED_CRIMSON_STEM: 40
    STRIPPED_DARK_OAK_LOG: 25
    STRIPPED_JUNGLE_LOG: 25
    STRIPPED_MANGROVE_LOG: 40
    STRIPPED_OAK_LOG: 25
    STRIPPED_PALE_OAK_LOG: 40
    STRIPPED_SPRUCE_LOG: 25
    STRIPPED_WARPED_HYPHAE: 40
    STRIPPED_WARPED_STEM: 40
    WARPED_HYPHAE: 40
    WARPED_STEM: 40
ability-configuration:
  extra-lumber:
    enabled: true
    activation-equation: (woodcutting_level)*.033
    valid-drops:
      - ACACIA_LEAVES
      - ACACIA_LOG
      - BIRCH_LEAVES
      - BIRCH_LOG
      - CHERRY_LEAVES
      - CHERRY_LOG
      - DARK_OAK_LEAVES
      - DARK_OAK_LOG
      - JUNGLE_LEAVES
      - JUNGLE_LOG
      - MANGROVE_LEAVES
      - MANGROVE_LOG
      - MANGROVE_ROOTS
      - OAK_LEAVES
      - OAK_LOG
      - SPRUCE_LEAVES
      - SPRUCE_LOG
      - WARPED_STEM
      - CRIMSON_STEM
      - MUSHROOM_STEM
      - RED_MUSHROOM_BLOCK
      - BROWN_MUSHROOM_BLOCK
  heavy-swing:
    enabled: true
    valid-blocks:
      - ACACIA_LEAVES
      - ACACIA_LOG
      - BIRCH_LEAVES
      - BIRCH_LOG
      - CHERRY_LEAVES
      - CHERRY_LOG
      - DARK_OAK_LEAVES
      - DARK_OAK_LOG
      - JUNGLE_LEAVES
      - JUNGLE_LOG
      - MANGROVE_LEAVES
      - MANGROVE_LOG
      - MANGROVE_ROOTS
      - OAK_LEAVES
      - OAK_LOG
      - SPRUCE_LEAVES
      - SPRUCE_LOG
      - WARPED_STEM
      - CRIMSON_STEM
      - MUSHROOM_STEM
      - RED_MUSHROOM_BLOCK
      - BROWN_MUSHROOM_BLOCK
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        activation-chance: 3.0
        radius: 1
      tier-2:
        unlock-level: 2
        activation-chance: 4.0
        radius: 1
      tier-3:
        unlock-level: 3
        activation-chance: 5.0
        radius: 1
      tier-4:
        unlock-level: 4
        activation-chance: 7.5
        radius: 2
      tier-5:
        unlock-level: 5
        activation-chance: 10.0
        radius: 2
  dryads-gift:
    enabled: true
    valid-blocks:
      - ACACIA_LEAVES
      - ACACIA_LOG
      - BIRCH_LEAVES
      - BIRCH_LOG
      - CHERRY_LEAVES
      - CHERRY_LOG
      - DARK_OAK_LEAVES
      - DARK_OAK_LOG
      - JUNGLE_LEAVES
      - JUNGLE_LOG
      - MANGROVE_LEAVES
      - MANGROVE_LOG
      - MANGROVE_ROOTS
      - OAK_LEAVES
      - OAK_LOG
      - SPRUCE_LEAVES
      - SPRUCE_LOG
      - WARPED_STEM
      - CRIMSON_STEM
      - MUSHROOM_STEM
      - RED_MUSHROOM_BLOCK
      - BROWN_MUSHROOM_BLOCK
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        activation-chance: 3.0
        experience-to-drop: 5
      tier-2:
        unlock-level: 2
        activation-chance: 4.0
        experience-to-drop: 10
      tier-3:
        unlock-level: 3
        activation-chance: 5.0
        experience-to-drop: 15
      tier-4:
        unlock-level: 4
        activation-chance: 7.5
        experience-to-drop: 20
      tier-5:
        unlock-level: 5
        activation-chance: 10.0
        experience-to-drop: 22
  nymphs-vitality:
    enabled: true
    valid-biomes:
      - BAMBOO_JUNGLE
      - BIRCH_FOREST
      - CHERRY_GROVE
      - CRIMSON_FOREST
      - DARK_FOREST
      - FLOWER_FOREST
      - FOREST
      - GROVE
      - JUNGLE
      - LUSH_CAVES
      - MANGROVE_SWAMP
      - OLD_GROWTH_BIRCH_FOREST
      - OLD_GROWTH_PINE_TAIGA
      - OLD_GROWTH_SPRUCE_TAIGA
      - SNOWY_TAIGA
      - SPARSE_JUNGLE
      - SWAMP
      - TAIGA
      - WARPED_FOREST
      - WINDSWEPT_FOREST
      - WOODED_BADLANDS
    #How many tiers does this ability have
    amount-of-tiers: 5
    #Configure the values for each tier
    tier-configuration:
      #Any value provided here will be default for each tier unless overridden by a tier
      #Accepted keys are as follows:
      # - upgrade-point-cost: integer
      # - unlock-level: integer
      # - upgrade-quest: quest
      all-tiers:
        # Ignored for tier 1
        upgrade-point-cost: 1
        upgrade-quest:
          kill-criteria:
            criteria-type: KILL_MOBS
            progression-required: 20*(tier^2)
            criteria-filter-mode: ALLOW
            criteria-filter:
              - SPIDER
              - CAVE_SPIDER
      tier-1:
        unlock-level: 1
        minimum-hunger: 7
      tier-2:
        unlock-level: 2
        minimum-hunger: 9
      tier-3:
        unlock-level: 3
        minimum-hunger: 11
      tier-4:
        unlock-level: 4
        minimum-hunger: 13
      tier-5:
        unlock-level: 5
        minimum-hunger: 15
